const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);const idle=()=>page.waitForFunction(()=>!state.busy&&!document.getElementById('notice').hidden?false:!state.busy);
 const open=async title=>{await page.locator('#course-list').getByRole('button',{name:new RegExp(title)}).click();await page.waitForFunction(t=>state.page==='course'&&state.data?.course.title===t,title).catch(async e=>{console.error('OPEN STATE',await page.evaluate(()=>({page:state.page,notice:document.getElementById('notice').textContent})),errors);throw e});};
 const answer=async option=>{const form=page.locator('#learning-loop-panel .loop-assessment form');await form.waitFor();await form.locator(`input[value="${option}"]`).check({force:true}).catch(async()=>{for(const n of await form.locator(`input[value="${option}"]`).all())await n.check({force:true});});for(const select of await form.locator('[data-confidence-index]').all())await select.selectOption('high');await form.getByRole('button',{name:'提交短检测',exact:true}).click();await idle();};
 await page.goto(process.env.MINDOS_TEST_URL);await open('闭环补强课程');const cid=await page.evaluate(()=>state.courseId),ordinal=await page.evaluate(()=>state.data.course.current_ordinal);assert.equal(ordinal,2);
 await page.locator('#learning-loop-panel').getByRole('button',{name:'开始约 5 分钟补强'}).click();await idle();assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.active_repair.target_atom_id),'a1');
 await page.locator('#learning-loop-panel').getByRole('button',{name:'开始短诊断'}).click();await idle();await page.reload();await open('闭环补强课程');assert.equal(await page.locator('#learning-loop-panel .loop-assessment').count(),1);await answer('b');
 await page.locator('#learning-loop-panel').getByRole('button',{name:'看短讲解与例子'}).click();await idle();assert(await page.locator('#learning-loop-panel .teaching-block').count()>=3);
 if(process.env.MINDOS_SCREENSHOTS)await page.locator('#learning-loop-panel').screenshot({path:'docs/validation/learning-loop-repair.png'});
 await page.locator('#learning-loop-panel').getByRole('button',{name:'做补强检测'}).click();await idle();await answer('a');assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.active_repair),null);assert.equal(await page.evaluate(()=>state.data.section.ordinal),2);assert.equal(await page.evaluate(()=>state.data.course.current_ordinal),2);
 await page.evaluate(()=>{setCourseMode('map');return openAtom('a1')});await page.locator('#atom-learning-details').click();await page.waitForFunction(()=>document.getElementById('atom-learning-state').textContent.includes('迁移'));assert.match(await page.locator('#atom-learning-state').textContent(),/未测/);assert.equal(await page.evaluate(()=>state.data.knowledge.atoms.find(a=>a.id==='a1').knowledge_state.state==='mastered'),false);
 await open('间隔复习课程');assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.returning_session),null);const before=await page.evaluate(()=>state.data.knowledge.learning_loop.states.a1.stability);await page.locator('#learning-loop-panel').getByRole('button',{name:'QKV · 回忆检测',exact:true}).click();await idle();await answer('a');assert(await page.evaluate(b=>state.data.knowledge.learning_loop.states.a1.stability>b,before));
 await open('中断恢复课程');assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.returning_session.status),'pending');const sid=await page.evaluate(()=>state.data.knowledge.learning_loop.returning_session.id);await page.reload();await open('中断恢复课程');assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.returning_session.id),sid);
 if(process.env.MINDOS_SCREENSHOTS)await page.locator('#learning-loop-panel').screenshot({path:'docs/validation/learning-loop-returning.png'});
 for(const title of ['QKV','Multi Head']){await page.locator('#learning-loop-panel').getByRole('button',{name:'回忆检测：'+title,exact:true}).click();await idle();await answer('a');}
 assert.equal(await page.evaluate(()=>state.data.knowledge.learning_loop.returning_session),null);assert.equal(await page.evaluate(()=>state.data.course.current_ordinal),2);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS: short diagnosis, micro teaching, persisted pending assessment, successful return to origin without advance; state reasons and unknown transfer; delayed review grows stability; returning check survives refresh and finishes; mobile.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
