const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);
 const open=async title=>{await page.locator('#course-manager-open').click();await page.locator('.manager-course-card').filter({hasText:title}).getByRole('button',{name:'进入学习',exact:true}).click();await page.waitForFunction(t=>state.data?.course.title===t,title);await page.evaluate(async()=>{setCourseMode('map');await openAtom('same-local-id');});await page.locator('.personal-atom-card').waitFor({timeout:7000}).catch(async e=>{console.error(await page.evaluate(()=>({personal:typeof MindOSPersonal,atom:state.atomDetail,notice:document.querySelector('#notice')?.textContent,panel:document.querySelector('#atom-personal')?.innerHTML,hidden:document.querySelector('#atom-panel')?.hidden})));throw e;});};
 await page.goto(process.env.MINDOS_TEST_URL);await open('LLM当前课程');const card=page.locator('.personal-atom-card');await card.getByText('你以前学过相关知识',{exact:true}).waitFor();await card.getByRole('button',{name:'快速确认已有基础',exact:true}).click();await card.locator('input[type=radio]').first().waitFor();
 await card.locator('input[type=radio][value=a]').nth(0).check();await card.locator('input[type=radio][value=a]').nth(1).check();await card.getByRole('button',{name:/提交/}).click();await card.getByText('✓ 已在本课程独立验证相关基础，讲解可以简短回顾，章节仍需手动推进。',{exact:true}).waitFor();
 if(process.env.MINDOS_SCREENSHOTS)await card.screenshot({path:'docs/validation/learning-loop-p3-desktop.png'});
 await page.reload();await open('LLM当前课程');await card.getByText('✓ 已在本课程独立验证相关基础，讲解可以简短回顾，章节仍需手动推进。',{exact:true}).waitFor();
 await open('LLM候选拒绝');await card.getByRole('button',{name:'不是同一个知识',exact:true}).click();await card.getByRole('button',{name:'检查相关历史知识',exact:true}).waitFor();await page.reload();await open('LLM候选拒绝');await card.getByRole('button',{name:'检查相关历史知识',exact:true}).waitFor();
 await open('LLM候选关联');await card.getByRole('button',{name:'确认关联',exact:true}).click();await card.getByRole('button',{name:'取消关联',exact:true}).waitFor();await page.reload();await open('LLM候选关联');await card.getByRole('button',{name:'取消关联',exact:true}).click();await card.getByRole('button',{name:'检查相关历史知识',exact:true}).waitFor();
 await page.locator('#personal-open').click();await page.getByRole('heading',{name:'个人知识档案',exact:true}).waitFor();await page.locator('.personal-knowledge-card').first().locator('summary').click();await page.getByRole('button',{name:'查看来源课程',exact:true}).first().click();await card.waitFor();
 await page.setViewportSize({width:390,height:844});await page.locator('#personal-open').click();await page.getByRole('heading',{name:'个人知识档案',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(process.env.MINDOS_SCREENSHOTS)await page.locator('#growth-profile').screenshot({path:'docs/validation/learning-loop-p3-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS P3: related history → UI quick diagnosis → real submit → persisted verified status; candidate confirm/revoke + refresh; profile source navigation; desktop/mobile no overflow.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
