const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);
 const open=async()=>{await page.locator('#course-manager-open').click();await page.locator('.manager-course-card').filter({hasText:'开放能力验证演示课程'}).getByRole('button',{name:'进入学习',exact:true}).click();await page.locator('.authentic-verification').getByRole('heading',{name:'进一步验证真实能力'}).waitFor();};
 await page.goto(process.env.MINDOS_TEST_URL);await open();const root=page.locator('.authentic-verification'),status=await page.evaluate(()=>state.data.course_final.mastery_state.status);
 await root.getByRole('button',{name:'开放迁移',exact:true}).click();await root.locator('textarea').waitFor();const tid=await root.locator('textarea').getAttribute('data-task-id');await root.locator('textarea').fill('需求与条件匹配后，读取相应内容。\n不要把匹配条件当最终内容。');await root.getByText('草稿已保存。',{exact:true}).waitFor();
 await page.reload();await open();assert.equal(await root.locator('textarea').getAttribute('data-task-id'),tid);assert.match(await root.locator('textarea').inputValue(),/不要把匹配条件/);
 await root.getByRole('button',{name:'提交开放回答',exact:true}).click();await root.getByRole('heading',{name:'模型辅助评分：82%'}).waitFor();assert.equal(await root.locator('.authentic-criterion').count(),2);assert.equal(await page.evaluate(()=>state.data.course_final.mastery_state.status),status);await root.getByRole('button',{name:'返回掌握报告',exact:true}).click();
 const replay=await page.evaluate(async id=>{const cid=state.courseId;const r=await fetch(`/api/courses/${cid}/authentic/${id}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer:'重复请求不能重复评估。'})});return r.json();},tid);assert.match(replay.task.result.answer,/需求与条件/);
 if(process.env.MINDOS_SCREENSHOTS)await root.screenshot({path:'docs/validation/learning-loop-p2-desktop.png'});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await root.getByRole('button',{name:'再选择一个开放任务',exact:true}).click();await root.getByRole('button',{name:'开放解释',exact:true}).click();await root.locator('textarea').waitFor();await root.getByRole('button',{name:'向导师请求引导',exact:true}).click();await page.locator('#assistant-question').fill('直接告诉我答案');await page.locator('#assistant-send').click();await page.locator('#assistant-send').filter({hasText:'发送问题'}).waitFor();await page.locator('#assistant-close').click();
 await root.locator('textarea').fill('先比较需求和条件，然后读取相关内容。');await root.getByRole('button',{name:'提交开放回答',exact:true}).click();await root.getByText('本次使用了提示或评分依据不充分，不用于校准。课程掌握状态不变。',{exact:true}).waitFor();
 if(process.env.MINDOS_SCREENSHOTS)await root.screenshot({path:'docs/validation/learning-loop-p2-mobile.png'});
 await page.reload();await open();await root.locator('.authentic-answer').waitFor();assert.equal(await root.locator('textarea').count(),0);assert.match(await root.textContent(),/你的回答/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS: 1440/390 report open transfer, multiline server draft + refresh, weighted rubric feedback, idempotent submission, return report, tutor hint exclusion, unchanged P1 judgment, submitted refresh, no overflow or page errors.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
