const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);await page.goto(process.env.MINDOS_TEST_URL);await page.locator('#growth-roadmap-open').click();const root=page.locator('#growth-roadmap');await root.locator('.growth-create').waitFor();await root.locator('[name=title]').fill('LLM 信息匹配应用');await root.locator('[name=description]').fill('独立理解QKV分工，能应用到具体任务');await root.locator('[name=weekly_time_budget_minutes]').fill('120');await root.getByRole('button',{name:'保存并分析能力',exact:true}).click();await root.getByRole('heading',{name:'审查能力草稿',exact:true}).waitFor();
 await root.locator('.growth-capability').filter({hasText:'额外阅读'}).getByRole('button',{name:'移除这项能力',exact:true}).click();await root.getByRole('button',{name:'增加自定义能力',exact:true}).click();const custom=root.locator('.growth-capability').last();await custom.locator('[name=name]').fill('工具阅读习惯');await custom.locator('[name=importance]').selectOption('optional');await root.getByRole('heading',{name:'审查能力草稿',exact:true}).click();await root.getByRole('button',{name:'确认能力结构',exact:true}).click();await root.getByRole('button',{name:'生成成长路线',exact:true}).waitFor();await root.getByRole('button',{name:'生成成长路线',exact:true}).click();await root.locator('.growth-route[data-version="1"]').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.MINDOS_SCREENSHOTS)await root.screenshot({path:'docs/validation/learning-loop-p4-desktop.png'});
 const task=root.locator('.growth-task').filter({hasText:'QKV'}).first();await task.getByRole('button',{name:'打开任务',exact:true}).click();await page.waitForFunction(()=>state.data?.course.title==='LLM当前目标课程');await page.locator('#learning-loop-panel:not([hidden]) input[type=radio], #atom-tests input[type=radio]').first().waitFor();const quiz=await page.locator('#atom-tests input[type=radio]').first().isVisible()?page.locator('#atom-tests'):page.locator('#learning-loop-panel');await quiz.locator('input[type=radio][value=a]').nth(0).check();await quiz.locator('input[type=radio][value=a]').nth(1).check();await quiz.getByRole('button',{name:/提交/}).click();await page.waitForFunction(()=>!state.busy);await page.locator('#growth-return').getByRole('button').click();await root.getByText('当前目标要求已基本满足',{exact:true}).waitFor();await root.getByRole('button',{name:'重新规划',exact:true}).click();await root.locator('.growth-route[data-version="2"]').waitFor();await root.getByText('你主动重新规划',{exact:true}).waitFor();await root.locator('[name=version]').selectOption('1');await root.getByText('正在查看旧版本，仅供回顾。',{exact:true}).waitFor();await root.locator('[name=version]').selectOption('2');
 await root.getByRole('button',{name:'暂停目标',exact:true}).click();await root.getByRole('button',{name:'恢复目标',exact:true}).waitFor();await root.getByRole('button',{name:'恢复目标',exact:true}).click();await root.getByRole('button',{name:'暂停目标',exact:true}).waitFor();await root.getByRole('button',{name:'编辑目标',exact:true}).click();await root.locator('.growth-editor [name=title]').fill('LLM目标 · 提升深度');await root.getByRole('button',{name:'保存目标修改',exact:true}).click();await root.getByText('目标或能力要求发生变化，当前路线需要更新。请重新规划。',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.MINDOS_SCREENSHOTS)await root.screenshot({path:'docs/validation/learning-loop-p4-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS P4: goal create → edit capability draft → confirm → roadmap v1 → current course independent quiz → return and evaluate → roadmap v2/reasons/history → pause/resume/edit/stale; desktop1440/mobile390 no overflow.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
