const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1100}});await context.addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);let page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.MINDOS_TEST_URL);await page.getByRole('heading',{name:'今天学习',exact:true}).waitFor();const card=page.locator('.study-today-task').first();await card.getByRole('button',{name:'打开建议任务',exact:true}).click();await page.locator('#study-entry:not([hidden])').waitFor();
 assert.equal(await page.evaluate(async()=>!(await api('/api/study/sessions/current')).session),true);await page.locator('#study-entry').getByRole('button',{name:'开始本次学习',exact:true}).click();const bar=page.locator('#study-session-bar');await bar.getByText('正在学习',{exact:true}).waitFor();await bar.getByRole('button',{name:'暂停',exact:true}).click();await bar.getByText('已暂停',{exact:true}).waitFor();await page.reload();await bar.getByText('已暂停',{exact:true}).waitFor();await bar.getByRole('button',{name:'继续',exact:true}).click();await bar.getByText('正在学习',{exact:true}).waitFor();
 await bar.getByRole('button',{name:'回到本次课程',exact:true}).click();await page.locator('#study-entry:not([hidden])').waitFor();
 // Complete a real synthetic quiz through unchanged P0; ending the session does not create this evidence.
 await page.evaluate(async()=>{const atom=state.data?.knowledge.atoms[0];if(atom){await MindOSLearningLoop.check(state.courseId,atom.id,'diagnostic');}});
 const quiz=page.locator('#learning-loop-panel');await quiz.locator('input[type=radio][value=a]').nth(0).check();await quiz.locator('input[type=radio][value=a]').nth(1).check();await quiz.getByRole('button',{name:/提交/}).click();await page.waitForFunction(()=>!state.busy);await bar.getByRole('button',{name:'结束本次学习',exact:true}).click();let dialog=page.getByRole('dialog',{name:'结束本次学习记录'});await dialog.locator('[name=completion]').selectOption('done');await dialog.locator('[name=reason]').selectOption('finished');await dialog.locator('[name=adjusted_active_minutes]').fill('35');await dialog.getByRole('button',{name:'保存并结束',exact:true}).click();await bar.waitFor({state:'hidden'});
 await page.locator('#dashboard-open').click();await page.getByRole('heading',{name:'今天学习',exact:true}).waitFor();await page.getByText('根据你过去类似任务调整',{exact:true}).first().waitFor();assert.equal(await page.evaluate(async()=>{const r=await api('/api/growth/today');return r.today.some(t=>t.pace_reason==='PACE_PERSONALIZED'&&t.predicted_minutes===35);}),true);
 if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p5-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'查看学习执行记录',exact:true}).click();dialog=page.getByRole('dialog',{name:'学习执行记录'});await dialog.locator('.study-history-row').first().getByText('关联答题 1 次',{exact:false}).waitFor();await dialog.locator('.study-history-row').first().getByRole('button',{name:'修正时间',exact:true}).click();await dialog.locator('.study-edit input').fill('25');await dialog.getByRole('button',{name:'保存修正',exact:true}).click();await dialog.getByRole('button',{name:'关闭',exact:true}).click();
 // Close the page and create a new one using the same cookie; active records are server-owned.
 await page.locator('#dashboard-open').click();await page.locator('.study-today-task').first().getByRole('button',{name:'打开建议任务'}).click();await page.locator('#study-entry').getByRole('button',{name:'开始本次学习',exact:true}).click();await page.close();page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.MINDOS_TEST_URL);await page.locator('#study-session-bar').getByText('正在学习',{exact:true}).waitFor();await page.getByRole('heading',{name:'今天学习',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#study-session-bar').getByRole('button',{name:'隐藏时间',exact:true}).click();await page.getByText('计时已隐藏',{exact:true}).waitFor();await page.emulateMedia({reducedMotion:'reduce'});
 if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p5-mobile.png',fullPage:true});
 await page.locator('#study-session-bar').getByRole('button',{name:'结束本次学习',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'保存并结束',exact:true}).click();await page.locator('#study-session-bar').waitFor({state:'hidden'});
 // Simulate stale timestamps only in the disposable fixture, then exercise the real recovery API.
 await page.locator('.study-today-task').first().getByRole('button',{name:'打开建议任务'}).click();await page.locator('#study-entry').getByRole('button',{name:'开始本次学习',exact:true}).click();await page.evaluate(()=>api('/__test__/interrupt-study',{}));await page.reload();await page.getByText('检测到未正常结束的学习记录，离线时间未计入。',{exact:true}).waitFor();await page.locator('#study-session-bar').getByRole('button',{name:'继续',exact:true}).click();await page.locator('#study-session-bar').getByText('正在学习',{exact:true}).waitFor();await page.locator('#study-session-bar').getByRole('button',{name:'修改时间',exact:true}).click();await page.getByRole('dialog').locator('[name=adjusted_active_minutes]').fill('12');await page.getByRole('dialog').getByRole('button',{name:'保存并结束',exact:true}).click();await page.locator('#study-session-bar').waitFor({state:'hidden'});assert.deepEqual(errors,[]);
 console.log('PASS P5: Today → open task (no timer) → explicit start → pause → refresh → resume → independent quiz → end → personalized estimate → edit history; page close/reopen recovery; interrupted UI; desktop1440/mobile390 no overflow, reduced motion.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
