const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postDataJSON?.()}));
 await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);await page.goto(process.env.MINDOS_TEST_URL);
 await page.locator('#personal-open').click();await page.locator('#knowledge-universe-open').click();await page.waitForFunction(()=>state.page==='universe'&&document.querySelectorAll('.ku-target').length===3);
 const fixture=()=>page.evaluate(()=>fetch('/api/p7-fixture').then(r=>r.json())),initial=await fixture();
 const enter=async()=>{await page.locator('.ku-target').filter({hasText:'Transformer宇宙验收'}).click();await page.waitForFunction(()=>document.querySelector('#ku-level').textContent==='章节星云');await page.locator('.ku-target').filter({hasText:'Attention机制'}).click();await page.waitForFunction(()=>document.querySelectorAll('.ku-target').length===2&&document.querySelector('#ku-level').textContent==='知识星辰');};
 const backToMap=async name=>{await page.locator('#knowledge-space h1').getByText(name,{exact:true}).waitFor();await page.locator('#knowledge-space').getByRole('button',{name:'← 返回知识星图',exact:true}).click();};
 const star=async name=>{await page.locator('.ku-target').filter({hasText:name}).click();await backToMap(name);await page.locator('#ku-detail h2').getByText(name,{exact:true}).waitFor();};
 await enter();await star('Attention');assert.equal((await fixture()).digest,initial.digest);assert.equal(await page.locator('#ku-detail').getByText('已有独立答题记录',{exact:true}).count(),1);
 await page.locator('.ku-relation').filter({hasText:'前置知识 · QKV'}).click();await page.locator('#ku-orbit-detail').getByText('为什么连接？',{exact:true}).waitFor();await page.locator('#ku-tutor-open').click();await page.waitForFunction(()=>!document.getElementById('assistant-question').disabled);await page.locator('#assistant-question').fill('为什么Attention需要先匹配再加权？');const graphReads=requests.filter(r=>r.url.includes('/api/universe')).length;
 await page.locator('#assistant-send').click();await page.waitForFunction(()=>!document.getElementById('assistant-send').disabled);assert.equal(await page.locator('.assistant-chat-message.assistant').count(),1);assert.equal(requests.filter(r=>r.url.includes('/api/universe')).length,graphReads);assert.equal((await fixture()).digest,initial.digest);const calls=(await fixture()).calls;assert.equal(calls.at(-1).context_id,initial.first_id);assert.equal(calls.at(-1).atom_id,'attention');
 const req=requests.find(r=>r.url.endsWith('/api/tutor/chat'));assert.equal(req.body.current_context.knowledge_atom_id,'attention');assert.equal(Object.hasOwn(req.body,'mastery'),false);
 await page.locator('#assistant-drag-handle').press('Alt+ArrowLeft');await page.locator('#assistant-resize-handle').press('Alt+ArrowLeft');const rect=await page.locator('#assistant-panel').boundingBox();await page.locator('#assistant-toggle').click();
 await page.locator('#ku-zoom-in').click();const scale=await page.evaluate(()=>MindOSKnowledgeUniverse.performance().transform.scale);await page.reload();await page.locator('#ku-detail h2').getByText('Attention',{exact:true}).waitFor();await page.locator('#ku-tutor-open').click();await page.waitForFunction(()=>!document.getElementById('assistant-question').disabled);assert.equal(await page.locator('.assistant-chat-message.assistant').count(),1);const restored=await page.locator('#assistant-panel').boundingBox();assert(Math.abs(rect.width-restored.width)<2);assert(Math.abs(rect.x-restored.x)<2);await page.locator('#assistant-toggle').click();assert.equal((await fixture()).digest,initial.digest);
 // A genuine P0 submission changes only the pre-existing engine. The UI reads it on the existing change event.
 const before=await page.locator('#ku-detail').innerText();await page.evaluate(async()=>{await fetch('/api/p7-fixture-evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});MindOSKnowledgeUniverse.notifyChange('/api/quizzes/submit','POST');});await page.waitForFunction(()=>document.getElementById('ku-detail').textContent.includes('独立答题通过'));assert.notEqual(await page.locator('#ku-detail').innerText(),before);
 if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p7-desktop.png',fullPage:true});
 await page.locator('#ku-back').click();await page.waitForFunction(()=>document.querySelector('#ku-level').textContent==='章节星云');await page.locator('.ku-target').filter({hasText:'后续进阶'}).click();await star('Multi-head Attention');assert.equal(await page.locator('#ku-tutor-open').isDisabled(),true);assert.equal(await page.evaluate(()=>state.universeSelection.star.unlocked),false);
 await page.locator('#ku-search').fill('大图知识404');await page.locator('#ku-search-results').getByRole('button',{name:'知识点 · 大图知识404',exact:true}).click();await backToMap('大图知识404');await page.locator('#ku-detail h2').getByText('大图知识404',{exact:true}).waitFor();assert.equal(await page.locator('.ku-target').count(),5);await page.locator('#ku-pages').getByRole('button',{name:'上一批'}).click();await page.waitForFunction(()=>document.querySelectorAll('.ku-target').length===200);await page.locator('#ku-fit').click();
 const metrics=await page.evaluate(async()=>{const elapsed=[];for(let i=0;i<60;i++){const a=performance.now();MindOSKnowledgeUniverse.performance();document.getElementById('ku-canvas').dispatchEvent(new KeyboardEvent('keydown',{key:i%2?'ArrowLeft':'ArrowRight',bubbles:true}));await new Promise(requestAnimationFrame);elapsed.push(performance.now()-a);}return {...MindOSKnowledgeUniverse.performance(),frame_intervals:elapsed};});assert.equal(metrics.visible_nodes,200);assert(metrics.draw_milliseconds.every(n=>Number.isFinite(n)&&n<100));
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#ku-search').fill('Attention');await page.locator('#ku-search-results').getByRole('button',{name:'知识点 · Attention',exact:true}).first().click();await backToMap('Attention');await page.locator('#ku-detail h2').getByText('Attention',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#ku-canvas').scrollIntoViewIfNeeded();const canvas=await page.locator('#ku-canvas').boundingBox(),old=await page.evaluate(()=>({...MindOSKnowledgeUniverse.performance().transform}));await page.mouse.move(canvas.x+10,canvas.y+10);await page.mouse.down();await page.mouse.move(canvas.x+60,canvas.y+70,{steps:5});await page.mouse.up();const moved=await page.evaluate(()=>MindOSKnowledgeUniverse.performance().transform);assert.notEqual(moved.x,old.x);await page.locator('.ku-target').filter({hasText:'QKV'}).focus();await page.keyboard.press('Enter');await backToMap('QKV');await page.locator('#ku-detail h2').getByText('QKV',{exact:true}).waitFor();await page.locator('.ku-target').filter({hasText:'Attention'}).focus();await page.keyboard.press('Enter');await backToMap('Attention');await page.locator('#ku-detail h2').getByText('Attention',{exact:true}).waitFor();await page.locator('#ku-zoom-out').click();await page.locator('#ku-canvas').scrollIntoViewIfNeeded();const pinchRect=await page.locator('#ku-canvas').boundingBox();const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});const pinchBefore=await page.evaluate(()=>MindOSKnowledgeUniverse.performance().transform.scale);const touch=async(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y,id])=>({x,y,id,radiusX:1,radiusY:1}))});await touch('touchStart',[[pinchRect.x+100,pinchRect.y+120,1],[pinchRect.x+200,pinchRect.y+120,2]]);await touch('touchMove',[[pinchRect.x+75,pinchRect.y+120,1],[pinchRect.x+225,pinchRect.y+120,2]]);await touch('touchEnd',[]);assert((await page.evaluate(()=>MindOSKnowledgeUniverse.performance().transform.scale))>pinchBefore);const animation=await page.locator('.ku-target[data-selected=true] .ku-node-label').evaluate(n=>getComputedStyle(n).animationName);assert.equal(animation,'none');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p7-mobile.png',fullPage:true});
 await page.locator('#ku-profile-back').click();await page.getByRole('heading',{name:'个人知识档案',exact:true}).waitFor();assert.equal(await page.locator('#knowledge-universe').isHidden(),true);assert.deepEqual(errors,[]);
 const sorted=metrics.draw_milliseconds.slice().sort((a,b)=>a-b),frames=metrics.frame_intervals.slice().sort((a,b)=>a-b);const report={desktop:[1440,1000],mobile:[390,844],visible_nodes:200,draw_p95_ms:sorted[Math.floor(sorted.length*.95)],frame_p50_ms:frames[30],frame_p95_ms:frames[57],checks:['profile entry','3 levels','read-only selection','owned current tutor context','no per-chat graph refresh','drag/resize/history refresh','genuine P0 update','future scope','search outside 200','bounded pages','zoom/pan/pinch','keyboard selection after pan','reduced motion','mobile overflow','return navigation'],boundary:'Headless Edge measurements on this machine, not a guarantee across devices.'};require('node:fs').writeFileSync('docs/validation/learning-loop-p7-browser.json',JSON.stringify(report,null,2)+'\n');console.log('PASS P7 browser '+JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
