const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);await page.goto(process.env.MINDOS_TEST_URL);const fixture=()=>page.evaluate(()=>fetch('/api/p8-fixture').then(r=>r.json())),info=await fixture();
 await page.locator('#personal-open').click();await page.locator('#knowledge-universe-open').waitFor();const initial=await fixture();await page.locator('#knowledge-universe-open').click();await page.locator('.ku-target').filter({hasText:'Transformer多模态课程'}).click();await page.locator('.ku-target').filter({hasText:'Attention机制'}).click();await page.locator('.ku-target').filter({hasText:'QKV'}).click();await page.locator('#knowledge-space h1').getByText('QKV',{exact:true}).waitFor();assert.equal((await fixture()).digest,initial.digest);assert.equal((await fixture()).sessions,0);
 const tab=async label=>{await page.locator('#ks-tabs').getByRole('button',{name:new RegExp('^'+label)}).click();};
 await tab('公式');assert.equal(await page.locator('#ks-content math').count(),1);assert.equal(await page.locator('#ks-content').getByText('查询',{exact:true}).count(),1);await tab('图示');assert.equal(await page.locator('#ks-content svg').count(),1);await page.locator('#ks-content').getByRole('button',{name:'放大',exact:true}).click();assert.match(await page.locator('.ks-visual-surface').getAttribute('style'),/scale\(1.2\)/);await page.locator('#ks-content').getByRole('button',{name:'重置',exact:true}).click();
 await tab('代码');assert.equal(await page.locator('.ks-code .ks-keyword').count()>0,true);assert.match(await page.locator('.ks-code').innerText(),/def match/);assert.equal(await page.locator('#ks-content').getByRole('button',{name:'运行',exact:true}).count(),0);
 await page.locator('#ks-tools summary').click();await page.locator('#ks-upload-caption').fill('用户说明：蓝色方块表示输入，箭头表示信息关联。');await page.locator('#ks-upload-file').setInputFiles({name:'我的图.png',mimeType:'image/png',buffer:Buffer.from(initial.image_base64,'base64')});await page.locator('#ks-tools').getByRole('button',{name:'上传并关联当前知识点'}).click();await page.locator('#ks-tabs').getByRole('button',{name:/^图片/}).waitFor();await tab('图片');assert.equal(await page.locator('#ks-content img').count(),1);await page.locator('#ks-content img').evaluate(img=>img.decode());await page.locator('#ks-content').getByRole('button',{name:'问导师这份材料',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('assistant-question').disabled);await page.locator('#assistant-question').fill('请结合这个图片的文字说明解释信息关联。');await page.locator('#assistant-send').click();await page.waitForFunction(()=>!document.getElementById('assistant-send').disabled);assert.equal(await page.locator('.assistant-resource-source').count(),1);assert.equal((await fixture()).calls.at(-1).resource_ids.includes((await fixture()).calls.at(-1).focus),true);assert((await fixture()).calls.at(-1).texts.some(t=>t.includes('未看到图片')));await page.locator('#assistant-close').click();
 await page.locator('#ks-upload-file').setInputFiles({name:'章节资料.pdf',mimeType:'application/pdf',buffer:Buffer.from(initial.pdf_base64,'base64')});await page.locator('#ks-tools').getByRole('button',{name:'上传并关联当前知识点'}).click();await tab('参考');await page.locator('#ks-content').getByRole('textbox',{name:'PDF 页码'}).fill('2');await page.locator('#ks-content').getByRole('button',{name:'提取选中页面',exact:true}).click();await page.locator('#ks-tabs').getByRole('button',{name:/^摘录/}).waitFor();await tab('摘录');assert.match(await page.locator('#ks-content').innerText(),/SECOND/);assert.doesNotMatch(await page.locator('#ks-content').innerText(),/FIRST|THIRD/);await page.locator('#ks-content').getByRole('button',{name:'只根据这份材料提问',exact:true}).click();await page.locator('#assistant-question').fill('只根据这份材料，说明本页的含义。');await page.locator('#assistant-send').click();await page.waitForFunction(()=>!document.getElementById('assistant-send').disabled);let calls=(await fixture()).calls;assert.equal(calls.at(-1).mode,'resource_only');assert.equal(calls.at(-1).resource_ids.length,1);assert(calls.at(-1).texts.every(t=>!t.includes('FIRST')&&!t.includes('THIRD')));await page.locator('#assistant-close').click();assert.equal((await fixture()).digest,initial.digest);assert.equal((await fixture()).tasks,0);
 await page.setViewportSize({width:390,height:844});await tab('公式');assert.equal(await page.locator('#ks-content math').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await tab('图示');await page.locator('#ks-content').getByRole('button',{name:'放大',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p8-mobile.png',fullPage:true});
 await tab('总览');await page.locator('#ks-content').getByRole('button',{name:'开始本次学习计时'}).click();assert.equal((await fixture()).sessions,1);assert.equal((await fixture()).digest,initial.digest);await tab('实践');await page.locator('#ks-content').getByRole('button',{name:'进入独立实践'}).click();await page.locator('.authentic-input').waitFor();assert.equal((await fixture()).tasks,1);assert.equal((await fixture()).digest,initial.digest);assert.deepEqual(errors,[]);
 const report={date:'2026-10-04',desktop:[1440,1000],mobile:[390,844],checks:['P7 star opens full space','dynamic material tabs','native MathML formula','safe code highlight','diagram zoom reset','actual PNG upload and decode','image caption boundary','selected resource tutor citation','actual PDF page 2 extraction','resource-only context','no automatic mastery or timer','explicit P5 start','original P2 authentic task','mobile no overflow'],simulated_model:true,actual_browser_and_parsers:true};require('node:fs').writeFileSync('docs/validation/learning-loop-p8-browser.json',JSON.stringify(report,null,2)+'\n');console.log('PASS P8 browser '+JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
