const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message);});page.on('dialog',d=>d.accept());await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);await page.goto(process.env.MINDOS_TEST_URL);page.on('response',async r=>{if(r.url().includes('/api/missions')&&r.status()>=400)console.error('Mission HTTP',r.status(),await r.text());});const fixture=()=>page.evaluate(()=>fetch('/api/p9-fixture').then(r=>r.json())),initial=await fixture();
 await page.locator('#growth-roadmap-open').click();await page.getByRole('heading',{name:'把成长目标带进实践'}).waitFor();await page.getByRole('button',{name:'审查并创建实践项目'}).click();await page.getByRole('textbox',{name:'希望交付什么成果？'}).fill('比较tile延迟并写报告');await page.getByRole('button',{name:'确认创建',exact:true}).click();await page.getByRole('button',{name:'生成计划草稿',exact:true}).waitFor();assert.equal((await fixture()).counts.learning_missions,1);assert.equal((await fixture()).counts.mission_tasks,0);
 await page.getByRole('button',{name:'生成计划草稿',exact:true}).click();await page.getByRole('button',{name:'确认计划并启用项目'}).waitFor();assert.equal((await fixture()).counts.mission_tasks,0);await page.getByRole('button',{name:'确认计划并启用项目'}).click();await page.locator('[data-testid="mission-current-task"]').waitFor();assert.equal((await fixture()).counts.mission_tasks,3);
 await page.getByRole('button',{name:'开始任务',exact:true}).click();await page.getByRole('button',{name:'开始记录本次用时'}).click();await page.locator('#study-session-bar').waitFor();assert.equal((await fixture()).counts.study_sessions,1);assert.equal((await fixture()).digest,initial.digest);
 // End the original P5 timer; it must not finish the mission task.
 await page.evaluate(async()=>{const r=await fetch('/api/study/sessions/current').then(r=>r.json());await fetch('/api/study/sessions/'+r.session.id+'/end',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({completion:'done',reason:'finished'})});await MindOSStudy.refresh();});assert.equal(await page.getByRole('button',{name:'确认任务完成',exact:true}).count(),1);await page.getByRole('button',{name:'确认任务完成',exact:true}).click();await page.locator('.mission-waypoints').getByRole('button',{name:/记录基线 · 已完成/}).waitFor();await page.locator('.mission-waypoints button').filter({hasText:'Tile实验'}).click();await page.getByRole('button',{name:'开始任务',exact:true}).click();await page.getByRole('heading',{name:'实验记录',exact:true}).waitFor();
 await page.getByRole('button',{name:'上传产出',exact:true}).click();await page.getByLabel('产出类型',{exact:true}).selectOption('benchmark');await page.locator('#mission-workspace input[type=file]').setInputFiles({name:'benchmark.csv',mimeType:'text/csv',buffer:Buffer.from('tile,latency_ms\n16,1.8\n32,1.3\n64,1.7')});await page.getByRole('button',{name:'保存产出',exact:true}).click();await page.getByRole('button',{name:'预览与询问导师'}).click();await page.locator('.mission-preview table').waitFor();assert.equal((await fixture()).counts.knowledge_resources,0);
 await page.locator('#assistant-toggle').click();await page.waitForFunction(()=>!document.getElementById('assistant-question').disabled);await page.locator('#assistant-question').fill('只根据这份产出，解释延迟观测的含义。');await page.locator('#assistant-send').click();await page.waitForFunction(()=>!document.getElementById('assistant-send').disabled);assert.equal(await page.locator('.assistant-resource-source').count(),1);const call=(await fixture()).calls.at(-1);assert.equal(call.mode,'artifact_only');assert.equal(call.artifact_ids.length,1);assert.equal(call.quality_guidance,true);await page.locator('#assistant-close').click();assert.equal((await fixture()).digest,initial.digest);
 for(const [tile,ms]of [[16,1.8],[32,1.3],[64,1.7]]){await page.getByRole('button',{name:'记录一次实验',exact:true}).click();await page.getByRole('textbox',{name:'参数（每行 名称=值）',exact:true}).fill('tile='+tile);await page.getByRole('textbox',{name:'结果指标',exact:false}).fill('latency_ms='+ms);await page.getByRole('textbox',{name:'观察、结论与限制'}).fill('同一输入，机制原因待验证');await page.getByRole('button',{name:'保存实际记录'}).click();await page.getByRole('heading',{name:'实验记录',exact:true}).waitFor();}
 for(const i of [1,2,3])await page.getByRole('checkbox',{name:new RegExp('^实验 '+i+' ·')}).check();await page.getByRole('button',{name:'比较选中实验（2–5条）'}).click();await page.getByRole('heading',{name:'同名指标比较'}).waitFor();assert.match(await page.locator('.mission-current').innerText(),/最小值 1.3/);
 await page.getByRole('textbox',{name:'写下你自己的复盘'}).fill('32目前最快，原因还需测量。');await page.getByRole('checkbox',{name:'我确认这是自己的复盘内容'}).check();await page.getByRole('button',{name:'确认保存复盘'}).click();await page.getByText('32目前最快，原因还需测量。',{exact:true}).waitFor();assert.equal((await fixture()).counts.mission_reflections,1);assert.equal((await fixture()).digest,initial.digest);
 await page.setViewportSize({width:390,height:844});await page.getByRole('heading',{name:'实验记录',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#assistant-panel').isVisible(),false);await page.getByRole('button',{name:'上传产出',exact:true}).click();await page.getByLabel('产出类型',{exact:true}).selectOption('code');await page.locator('#mission-workspace input[type=file]').setInputFiles({name:'kernel.cu',mimeType:'text/plain',buffer:Buffer.from('__global__ void kernel(float* x) { x[0] = 1; }')});await page.getByRole('button',{name:'保存产出',exact:true}).click();await page.locator('.mission-artifact').filter({hasText:'kernel.cu'}).getByRole('button',{name:'预览与询问导师'}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const evidence=page.locator('.mission-card').filter({has:page.getByRole('heading',{name:'独立能力验证',exact:true})});await evidence.getByRole('checkbox',{name:/benchmark.csv/}).check();await evidence.getByRole('textbox',{name:'这份产出支持哪项能力声明？'}).fill('我可以独立设计可复现的延迟比较');await evidence.getByRole('button',{name:'确认保存待验证候选'}).click();await page.getByRole('heading',{name:'我可以独立设计可复现的延迟比较',exact:true}).waitFor();assert.equal((await fixture()).counts.project_evidence_candidates,1);assert.equal((await fixture()).digest,initial.digest);await page.getByRole('button',{name:'生成独立陌生任务'}).click();await page.locator('.authentic-input').waitFor();assert.equal((await fixture()).counts.authentic_tasks,1);assert.equal((await fixture()).digest,initial.digest);assert.deepEqual(errors,[]);
 const report={date:'2026-10-04',desktop:[1440,1000],mobile:[390,844],checks:['growth recommendation confirmed create','draft-only plan then confirm','explicit P5 timing end does not complete task','original milestone gates','CSV safe table preview','P6/P65 floating tutor selected artifact citation','three real user-recorded runs compared no cause','confirmed reflection','artifact/resource/evidence separation','mobile code upload preview no overflow','candidate to original independent P2 task'],synthetic_model:true,actual_browser_http_and_files:true};require('node:fs').writeFileSync('docs/validation/learning-loop-p9-browser.json',JSON.stringify(report,null,2)+'\n');console.log('PASS P9 browser '+JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
