const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.context().addCookies([{name:'mindos_session',value:process.env.MINDOS_TEST_COOKIE,url:process.env.MINDOS_TEST_URL,httpOnly:true,sameSite:'Strict'}]);
 const open=async()=>{await page.locator('#course-list').getByRole('button',{name:/Transformer导师验收课程/}).click();await page.waitForFunction(()=>state.page==='course'&&state.data?.course.title==='Transformer导师验收课程');await page.waitForFunction(()=>!document.getElementById('assistant-question').disabled);await page.locator('#assistant-toggle').click();};
 await page.goto(process.env.MINDOS_TEST_URL);await open();await page.locator('#assistant-question').fill('质量改写验收：解释QKV');await page.locator('#assistant-send').click();await page.waitForFunction(()=>!document.getElementById('assistant-send').disabled);
 await page.locator('#tutor-quality-debug').getByText(/quality: passed · retry: 1/).waitFor({state:"attached"});await page.locator('#tutor-quality-debug summary').click();assert.equal(await page.locator('.assistant-chat-message').count(),2);assert.equal(await page.locator('.assistant-chat-message.assistant .teaching-text').count()>0,true);assert.equal(await page.evaluate(()=>state.data.knowledge.tested_count),0);
 const handle=await page.locator('#assistant-drag-handle').boundingBox();await page.mouse.move(handle.x+80,handle.y+12);await page.mouse.down();await page.mouse.move(400,100,{steps:8});await page.mouse.up();const before=await page.locator('#assistant-panel').boundingBox();
 if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p65-desktop.png'});
 await page.reload();await open();const after=await page.locator('#assistant-panel').boundingBox();assert(Math.abs(before.x-after.x)<2);assert(Math.abs(before.y-after.y)<2);assert.equal(await page.locator('.assistant-chat-message').count(),2);await page.locator('#tutor-quality-debug').getByText(/quality: passed · retry: 1/).waitFor({state:"attached"});
 await page.setViewportSize({width:390,height:844});const mobile=await page.locator('#assistant-panel').boundingBox();assert(mobile.x>=0&&mobile.x+mobile.width<=390);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.MINDOS_SCREENSHOTS)await page.screenshot({path:'docs/validation/learning-loop-p65-mobile.png'});
 await page.locator('#tutor-clear-history').click();await page.waitForFunction(()=>document.querySelectorAll('.assistant-chat-message').length===0);await page.locator('#tutor-quality-debug').getByText('暂无回答质量记录。').waitFor({state:'attached'});assert.deepEqual(errors,[]);
 // Server gate controls both UI and endpoint; a client query cannot enable it.
 await page.setViewportSize({width:1440,height:1000});await page.route('**/api/bootstrap',async route=>{const r=await route.fetch();await route.fulfill({response:r,json:{...await r.json(),tutor_quality_debug_enabled:false}});});await page.reload();await open();assert.equal(await page.locator('#tutor-quality-debug').count(),0);
 console.log('PASS P6.5: one quality repair, developer-only minimal metadata, structured response, unchanged mastery, drag and refresh, bounded mobile layout, clear metadata and normal UI unchanged.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
