/* Macro planning reads learning outcomes; classroom modules retain their own controls. */
(() => {
 let selected=null,request=0,pendingPractice=null,creation=null;
 const types={skill:'技能',knowledge_domain:'知识领域',project:'项目',competition:'比赛',certificate:'考试 / 证书',custom:'自定义'};
 const levels={overview:'了解概况',understanding:'理解',practical_understanding:'理解并能使用',application:'应用',transfer:'迁移',advanced:'深入'};
 const capabilityTypes={knowledge:'知识',application:'应用能力',transfer:'迁移能力',tool:'工具使用',practice:'实践',meta_skill:'学习方法'};
 const importance={critical:'关键',supporting:'辅助',optional:'可选'};
 const depth={understanding:'理解',application:'应用',transfer:'迁移'};
 const statuses={planned:'待安排',ready:'可以开始',active:'正在进行',completed:'已有依据',blocked:'等待前置',skipped:'已跳过',paused:'已暂停',obsolete:'已失效'};
 const taskNames={continue_course:'继续现有课程',start_course:'打开已有课程',create_course:'审查新课程建议',review:'延迟回忆',cross_course_verify:'独立验证',final_assessment:'课程掌握检测',authentic_assessment:'开放实践',micro_practice:'小练习',goal_checkpoint:'审查能力要求'};
 const causes={USER_REQUESTED_REPLAN:'你主动重新规划',CAPABILITY_VERIFIED:'能力已获得验证依据',CAPABILITY_CONFLICT:'能力表现出现冲突',COURSE_MASTERED:'课程掌握检测已通过',COURSE_COMPLETED_WITH_GAPS:'课程完成后仍有缺口',MAJOR_MISCONCEPTION:'发现关键误区',PROFILE_CHANGED:'知识状态或保留情况变化',GOAL_CHANGED:'目标要求变化',DEADLINE_CHANGED:'时间要求变化'};
 function button(text,fn,primary=false){const b=node('button',text,'button '+(primary?'primary':'secondary'));b.type='button';b.onclick=()=>action(b,'正在更新成长路线…',fn);return b;}
 function input(parent,label,key,value='',type='text'){const l=node('label',label),i=node(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.name=key;i.value=value??'';if(type==='textarea')i.rows=3;l.append(i);parent.append(l);return i;}
 function select(parent,label,key,value,options){const l=node('label',label),s=node('select');s.name=key;for(const [v,t]of Object.entries(options)){const o=node('option',t);o.value=v;s.append(o);}s.value=value;l.append(s);parent.append(l);return s;}
 async function mutation(url,payload,method='PATCH'){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
 const path=(gid,op='')=>`/api/goals/${encodeURIComponent(gid)}${op?'/'+op:''}`;
 function goalFields(parent,g={}){const f=node('div','','growth-form');parent.append(f);input(f,'目标名称','title',g.title);input(f,'希望独立完成什么？','description',g.description,'textarea');select(f,'目标类型','goal_type',g.goal_type||'custom',types);select(f,'希望达到的深度','target_level',g.target_level||'practical_understanding',levels);input(f,'截止日期（可选）','deadline',g.deadline,'date');input(f,'每周可用分钟（可选）','weekly_time_budget_minutes',g.weekly_time_budget_minutes,'number');const p=input(f,'优先级（1最高，5最低）','priority',g.priority||1,'number');p.min=1;p.max=5;
  return ()=>Object.fromEntries([...f.querySelectorAll('[name]')].map(i=>[i.name,['priority','weekly_time_budget_minutes'].includes(i.name)?i.value?Number(i.value):null:i.name==='deadline'?i.value||null:i.value]));}
 async function show(gid=selected,version=null,evaluate=false){
  const token=++request;invalidateNavigation();MindOSUniverse.hideStandalone();MindOSUniverse.navigation('growth-roadmap');state.data=null;state.courseId=null;state.atomDetail=null;
  for(const id of ['welcome','review-view','course-view','course-management'])$(id).hidden=true;
  const root=$('growth-roadmap');root.hidden=false;root.replaceChildren(node('p','正在读取目标和路线…','muted'));$('breadcrumb').textContent='成长路线';
  const list=await api('/api/goals');if(token!==request||state.page!=='growth-roadmap')return;
  selected=list.goals.some(g=>g.id===gid)?gid:list.goals[0]?.id||null;
  root.replaceChildren(node('p','GOAL-DRIVEN GROWTH','eyebrow'),node('h1','把目标变成下一步'),node('p','先确认需要哪些能力，再用已有课程和独立验证补齐缺口。路线建议不会替你创建课程或推进章节。','muted'));
  const toolbar=node('div','','action-row');toolbar.append(button('新增学习目标',()=>newGoal(root),true));for(const g of list.goals)toolbar.append(button(g.title+(g.status==='paused'?' · 暂停':g.status==='achieved'?' · 当前要求已满足':''),()=>show(g.id)));root.append(toolbar);
  if(!selected){newGoal(root);return;}
  const gidNow=selected;let evaluated=null;if(evaluate)evaluated=await api(path(gidNow,'evaluate'),{});
  const [detail,coverage,roadmap]=await Promise.all([api(path(gidNow)),api(path(gidNow,'capabilities')),api(path(gidNow,'roadmap')+(version?'?version='+version:''))]);
  if(token!==request||state.page!=='growth-roadmap')return;const g=detail.goal;
  const card=node('section','','card growth-goal');card.append(node('h2',g.title),node('p',g.description||'以实际理解与应用为默认目标。'),node('small',`${types[g.goal_type]} · ${levels[g.target_level]} · ${g.weekly_time_budget_minutes?`每周约 ${g.weekly_time_budget_minutes} 分钟`:'未设时间预算'}${g.deadline?' · 截止 '+g.deadline:''}`,'muted'));
  if(g.clarification)card.append(node('p',g.clarification,'muted'));
  card.append(button('编辑目标',()=>editGoal(card,g)),button(g.status==='paused'?'恢复目标':'暂停目标',async()=>{await mutation(path(g.id),{status:g.status==='paused'?'active':'paused'});await show(g.id,null,true);}),button('删除目标',async()=>{if(!confirm('只删除这个目标及其路线，课程与学习记录保留。确定删除？'))return;await mutation(path(g.id),{},'DELETE');await show(null);}));root.append(card);
  if(g.requirements_stale)root.append(node('p','目标范围已变化。现有能力与缺口来自旧要求，请重新分析并确认能力草稿后再规划。','notice'));
  const raw=g.draft?.capabilities?.length?g.draft:g.graph;
  if(raw?.capabilities?.length)renderCapabilities(root,g,raw,coverage.mappings);
  else root.append(button('分析目标所需能力',async()=>{await api(path(g.id,'analyze'),{});await show(g.id);},true));
  if(g.graph?.capabilities?.length){const gaps=await api(path(g.id,'gaps'));if(token!==request||state.page!=='growth-roadmap')return;const section=node('section','','card growth-gaps');section.append(node('h2','目标缺口'),node('p',gaps.completion.label,'growth-completion'));
   const grid=node('div','','growth-gap-grid');for(const gap of gaps.gaps){const row=node('article','','growth-gap');row.dataset.gap=gap.status;row.append(node('strong',gap.name),node('p',gap.label),node('small',`${importance[gap.importance]} · 需要${depth[gap.required_level]} · ${gap.planning_confidence}`,'muted'));grid.append(row);}section.append(node('p',`已有依据 ${gaps.summary.sufficient||0} · 关键缺口 ${gaps.critical_gaps.length} · 待验证 ${(gaps.summary.unknown||0)+(gaps.summary.ready_to_verify||0)+(gaps.summary.conflicted||0)}`),grid,node('small',gaps.boundary,'muted'));root.append(section);
   if(roadmap.roadmap)renderRoadmap(root,g,roadmap,version,evaluated);else root.append(button('生成成长路线',async()=>{await api(path(g.id,'roadmap/generate'),{});await show(g.id);},true));}
  await window.MindOSStudy?.execution(root,g);
  if(new URLSearchParams(location.search).get('debug_learning')==='1'&&g.graph?.capabilities?.length)root.append(button('查看成长规划开发记录',async()=>{const d=await api('/api/debug/learning/growth/'+g.id+'/gaps');root.append(node('pre',JSON.stringify({goal:g,gaps:d,roadmap},null,2),'calibration-debug'));}));
 }
 function newGoal(root){const form=node('section','','card growth-create');root.querySelector('.growth-create')?.remove();root.prepend(form);form.append(node('h2','新增学习目标'));const values=goalFields(form);form.append(button('保存并分析能力',async()=>{const r=await api('/api/goals',values());selected=r.goal.id;await api(path(selected,'analyze'),{});await show(selected);},true));}
 function editGoal(parent,g){parent.querySelector('.growth-editor')?.remove();const editor=node('div','','growth-editor');parent.append(editor);const values=goalFields(editor,g);editor.append(button('保存目标修改',async()=>{await mutation(path(g.id),values());await show(g.id);}));}
 function rawGraph(graph){const names=Object.fromEntries(graph.capabilities.map(c=>[c.id,c.name]));return {goal_summary:graph.goal_summary,capabilities:graph.capabilities.map(c=>Object.fromEntries(['name','type','required_level','importance','description','concept_type'].filter(k=>k in c).map(k=>[k,c[k]]))),dependencies:graph.dependencies.map(e=>({...e,from:names[e.from],to:names[e.to]}))};}
 function renderCapabilities(root,g,graph,mappings){const section=node('section','','card growth-capabilities');section.append(node('h2',g.draft?.capabilities?.length?'审查能力草稿':'已确认的目标能力'),node('p','这是目标要求，不是你的掌握结论。删去关键能力会改变目标范围，跳过任务不会满足要求。','muted'));root.append(section);
  if(graph.source==='editable_rule_fallback')section.append(node('p','模型暂未提供有效能力草稿，当前是保守草稿，请补充具体能力后确认。','muted'));
  if(graph.ignored_soft_edges?.length)section.append(node('p','与前置顺序冲突的建议顺序已忽略。','muted'));
  const draft=rawGraph(graph),list=node('div','','growth-capability-list');section.append(list);
  function render(){list.replaceChildren();draft.capabilities.forEach((c,index)=>{const box=node('details','','growth-capability');box.open=Boolean(g.draft?.capabilities?.length);box.append(node('summary',`${c.name} · ${importance[c.importance]} · ${depth[c.required_level]}`));const f=node('div','','growth-form');box.append(f);const name=input(f,'能力名称','name',c.name),desc=input(f,'能力说明','description',c.description,'textarea'),kind=select(f,'能力类型','type',c.type,capabilityTypes),required=select(f,'要求深度','required_level',c.required_level,depth),imp=select(f,'重要程度','importance',c.importance,importance);
   for(const i of [name,desc,kind,required,imp])i.onchange=()=>{const old=c.name;c[i.name]=i.value;if(i===name)draft.dependencies.forEach(e=>{if(e.from===old)e.from=c.name;if(e.to===old)e.to=c.name;});};box.append(button('移除这项能力',()=>{draft.dependencies=draft.dependencies.filter(e=>e.from!==c.name&&e.to!==c.name);draft.capabilities.splice(index,1);render();}));list.append(box);});}
  render();section.append(button('增加自定义能力',()=>{draft.capabilities.push({name:'自定义能力 '+(draft.capabilities.length+1),type:'knowledge',required_level:'understanding',importance:'supporting',description:'请填写希望独立完成的能力。'});render();}));
  const edges=node('details');edges.append(node('summary','查看或编辑能力依赖（前置 → 后续）'));const textarea=node('textarea');textarea.rows=4;textarea.setAttribute('aria-label','能力依赖');textarea.value=draft.dependencies.map(e=>`${e.from} → ${e.to} | ${e.relation}`).join('\n');edges.append(textarea,node('small','每行填写：前置能力 → 后续能力 | prerequisite。也可使用 recommended_before 或 supports。能力名称须与上方一致。','muted'));section.append(edges);
  section.append(button(g.draft?.capabilities?.length?'确认能力结构':'保存能力调整',async()=>{if(textarea.value!==rawGraph(graph).dependencies.map(e=>`${e.from} → ${e.to} | ${e.relation}`).join('\n'))draft.dependencies=textarea.value.split('\n').filter(s=>s.trim()).map(line=>{const [pair,relation]=line.split('|'),parts=pair.split('→');if(parts.length!==2)throw Error('依赖格式不正确');return {from:parts[0].trim(),to:parts[1].trim(),relation:(relation||'prerequisite').trim()};});
   let current=g;if(!g.draft?.capabilities?.length)current=(await api(path(g.id,'analyze'),{})).goal;
   await api(path(g.id,'analyze'),{confirm:true,draft_version:current.draft_version,graph:draft});await show(g.id);},true),button('重新分析能力草稿',async()=>{await api(path(g.id,'analyze'),{});await show(g.id);}));
  if(g.graph?.capabilities?.length&&!g.requirements_stale)section.append(button('检查新增课程的知识关联',async()=>{await api(path(g.id,'capabilities/scan'),{});await show(g.id);}));
  for(const m of mappings.filter(m=>m.status==='candidate')){const row=node('div','','growth-mapping');row.append(node('p',`待审查关联：${graph.capabilities.find(c=>c.id===m.capability_id)?.name||'能力'} ↔ ${m.canonical_name}`),node('p',m.canonical_description||'定义暂未提供，请谨慎确认。','muted'),node('small',`原知识类型：${m.canonical_type||'未注明'} · 领域：${m.canonical_domain||'未注明'}`,'muted'),node('small','只有确认表达同一知识时才用于课程覆盖判断，不会继承课程掌握。','muted'));if(!['different','broader','narrower','related'].includes(m.relationship))row.append(button('确认同一知识',async()=>{await api(path(g.id,`mappings/${m.id}/verify`),{});await show(g.id);}));row.append(button('不采用这个关联',async()=>{await api(path(g.id,`mappings/${m.id}/reject`),{});await show(g.id);}));section.append(row);}
 }
 function renderRoadmap(root,g,result,version,evaluated){const plan=result.roadmap,section=node('section','','card growth-route');section.dataset.version=plan.version;section.append(node('h2',`成长路线 · v${plan.version}`));root.append(section);
  const historical=version&&version!==result.versions[0]?.version;const stale=plan.status==='stale';if(stale)section.append(node('p','目标或能力要求发生变化，当前路线需要更新。请重新规划。','notice'));if(historical)section.append(node('p','正在查看旧版本，仅供回顾。','muted'));if(evaluated?.replan_recommended)section.append(node('p','学习结果已有变化。为避免频繁调整，当前任务状态已更新；你可以点击重新规划生成新版本。','muted'));if(evaluated?.route_updated)section.append(node('p','路线已更新，请查看调整原因。','notice success'));
  const controls=node('div','','action-row');controls.append(button('检查最新学习结果',()=>show(g.id,null,true)),button('重新规划',async()=>{await api(path(g.id,'replan'),{});await show(g.id);},true));const chooser=select(controls,'路线版本','version',String(plan.version),Object.fromEntries(result.versions.map(v=>[v.version,'v'+v.version])));chooser.onchange=()=>show(g.id,Number(chooser.value));section.append(controls);
  const change=result.changes.find(c=>c.to_version===plan.version);if(change){const detail=node('details','','growth-changes');detail.open=true;detail.append(node('summary','这次调整的原因'),node('p',change.reason_codes.map(c=>causes[c]||c).join('、')));if(change.diff.added.length)detail.append(node('p','新增安排：'+change.diff.added.join('、')));if(change.diff.no_longer_required.length)detail.append(node('p','不再需要原安排：'+change.diff.no_longer_required.join('、')));section.append(detail);}
  for(const stage of plan.stages){const row=node('article','','growth-stage');row.dataset.stage=stage.ordinal;row.append(node('p',`${stage.ordinal} / ${plan.stages.length} · ${stage.status==='completed'?'阶段要求已有依据':stage.status==='active'?'当前阶段':'后续阶段'}`,'eyebrow'),node('h3',stage.title),node('p',stage.objective,'muted'));
   for(const t of plan.tasks.filter(t=>t.stage_ordinal===stage.ordinal)){const task=node('div','','growth-task');task.dataset.taskId=t.id;task.dataset.status=t.status;task.append(node('h4',t.title),node('p',`${taskNames[t.task_type]} · ${statuses[t.status]} · 约 ${t.estimated_minutes} 分钟`),node('p',t.reason,'muted'),node('small',t.metadata.why_after||'以实际验证结果决定下一阶段。','muted'));if(t.metadata.blocked_by?.length)task.append(node('p','先补齐：'+t.metadata.blocked_by.join('、')));if(t.metadata.blocked_note)task.append(node('p',t.metadata.blocked_note));
    if(!historical&&!stale){const buttons=node('div','','action-row');if(['ready','active','planned'].includes(t.status)){const start=button('打开任务',()=>startTask(g.id,t.id),true);start.disabled=stage.ordinal!==plan.current_stage||Boolean(t.metadata.deadline_deferred_optional||t.metadata.deferred_to_later_batch);buttons.append(start);}
     if(t.status!=='completed')buttons.append(button(t.status==='skipped'||t.status==='paused'?'恢复任务':'跳过',async()=>{await api(path(g.id,`tasks/${t.id}/${t.status==='skipped'||t.status==='paused'?'resume':'skip'}`),{});await show(g.id);}),button('暂停任务',async()=>{await api(path(g.id,`tasks/${t.id}/pause`),{});await show(g.id);}));
     buttons.append(button(t.locked?'取消固定':'固定任务',async()=>{await api(path(g.id,`tasks/${t.id}/lock`),{enabled:!t.locked});await show(g.id);}),button(t.pinned?'取消优先':'优先显示',async()=>{await api(path(g.id,`tasks/${t.id}/pin`),{enabled:!t.pinned});await show(g.id);}));task.append(buttons);}
    row.append(task);}section.append(row);}
  section.append(node('small','路线由规则安排，阶段标题可由模型协助组织。合理运行不代表已证明是最优教育路径。','muted'));
 }
 async function startTask(gid,tid){const result=await api(path(gid,`tasks/${tid}/start`),{}),r=result.route;selected=gid;window.MindOSStudy?.suggest(result.study_session_suggestion);
  if(r.destination==='growth'){showNotice(r.note);return;}
  if(r.destination==='create_course'){showWelcome();window.MindOSStudy?.suggest(result.study_session_suggestion);creation={growth_goal_id:gid,growth_task_id:tid};$('course-title-input').value=r.title;$('course-goal-input').value=r.goal;returnBar();return;}
  creation=null;await openCourse(r.course_id,undefined,r.destination==='atom'?'stars':'learn');if(state.courseId!==r.course_id||!state.data)throw Error('课程未能打开，请重试');returnBar();
  if(r.destination==='atom'){await openAtom(r.atom_id);if(r.prior_id){const data=await api(`/api/courses/${r.course_id}/knowledge/priors/${r.prior_id}/verify`,{});const root=$('atom-tests');if(root&&data.quiz?.available!==false)renderKnowledgeTests(root,[data.quiz],async()=>{await openAtom(r.atom_id);});}else{MindOSUniverse.viewCourse('learn');await MindOSLearningLoop.check(r.course_id,r.atom_id,r.assessment);}}
  if(r.destination==='final')$('course-final-panel')?.scrollIntoView({block:'start'});
  if(r.destination==='authentic'){pendingPractice={gid,tid,cid:r.course_id};const panel=$('growth-practice')||node('div');panel.id='growth-practice';$('course-view').append(panel);panel.replaceChildren();const data=await api(`/api/courses/${r.course_id}/final/status`);await MindOSAuthentic.render(panel,data.report,r.course_id,{atom_id:r.atom_id,task_type:r.assessment,growth_goal_id:gid,growth_task_id:tid});panel.scrollIntoView({block:'start'});}
 }
 function returnBar(){let bar=$('growth-return');if(!bar){bar=node('div','','growth-return');bar.id='growth-return';$('breadcrumb').after(bar);}bar.replaceChildren(button('← 返回成长路线并检查结果',()=>show(selected,null,true)));}
 async function attach(cid,task){if(!pendingPractice||cid!==pendingPractice.cid||task?.status!=='created')return;const p=pendingPractice;await api(path(p.gid,`tasks/${p.tid}/artifact`),{authentic_task_id:task.id});pendingPractice=null;}
 function creationContext(){return creation||{};}
 async function courseCreated(cid){if(!creation)return;await api(path(creation.growth_goal_id,`tasks/${creation.growth_task_id}/link-course`),{course_id:cid});creation=null;}
 function resetCreation(){creation=null;window.MindOSStudy?.clearSuggestion();}
 document.addEventListener('DOMContentLoaded',()=>{$('growth-roadmap-open').onclick=()=>show().catch(e=>showNotice(e.message));});
 window.MindOSGrowth={show,startTask,attach,creationContext,courseCreated,resetCreation};
})();
