/* Atom-specific material space. Selection has no assessment or progress side effects. */
window.MindOSKnowledgeSpace=(()=>{
 let detail=null,resources=[],offset=0,hasMore=false,tab='overview',focus=null,grounded=false,version=0,debug=false;const root=$('knowledge-space');
 const names={text:'讲解',formula:'公式',code:'代码',image:'图片',diagram:'图示',paper_excerpt:'摘录',reference:'参考',practice:'实践'};
 const button=(label,fn,primary=false)=>{const b=node('button',label,'button '+(primary?'primary':'secondary'));b.type='button';b.onclick=()=>action(b,'正在处理…',fn);return b;};
 async function call(path,payload,method='POST'){const r=await fetch(path,payload===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const v=await r.json();if(!r.ok)throw Error(v.error||'资料暂不可用');return v;}
 const path=()=>`/api/courses/${detail.atom.course_id}/atoms/${detail.atom.atom_id}/resources`;
 function active(){return detail&&state.page==='universe'&&!root.hidden;}
 function selection(){return active()?{focused_resource_id:focus,resource_grounded:grounded}:null;}
 async function load(more=false){const token=version,p=path(),q=$('ks-search').value.trim(),kind=$('ks-filter').value;const value=await call(p+'?'+new URLSearchParams({offset:more?offset:0,search:q,...(kind?{type:kind}:{})}));if(token!==version||!active())return;resources=more?[...resources,...value.resources]:value.resources;hasMore=value.has_more;offset=value.next_offset;render({...value.counts,examples:value.role_counts?.example||0});}
 async function show(data){version++;detail=data;focus=null;grounded=false;resources=[];tab='overview';root.hidden=false;$('knowledge-universe').hidden=true;root.replaceChildren();
  const header=node('header','','ks-header');header.append(button('← 返回知识星图',back),node('p',data.galaxy.name+' / '+data.nebula.name,'eyebrow'),node('h1',data.atom.name),node('p',data.atom.description,'ks-description'),node('p',data.atom.state_label+' · '+data.atom.state_basis,'muted'));root.append(header);
  const toolbar=node('div','','ks-toolbar'),search=document.createElement('input');search.id='ks-search';search.placeholder='搜索这个知识点的材料';search.maxLength=100;search.setAttribute('aria-label','搜索学习材料');search.onchange=()=>load().catch(report);const filter=document.createElement('select');filter.id='ks-filter';filter.setAttribute('aria-label','资料类型');filter.append(node('option','全部类型'));filter.firstChild.value='';for(const[k,n]of Object.entries(names)){const o=node('option',n);o.value=k;filter.append(o);}filter.onchange=()=>load().catch(report);toolbar.append(search,filter);root.append(toolbar);
  const tabs=node('nav','','ks-tabs');tabs.id='ks-tabs';tabs.setAttribute('aria-label','知识学习材料');const content=node('section');content.id='ks-content';const error=node('p','','notice error');error.id='ks-error';error.hidden=true;root.append(tabs,error,content);
  const tools=node('details','','ks-tools card');tools.id='ks-tools';tools.append(node('summary','添加、上传或生成学习材料'));root.append(tools);const nearby=node('section','','card ks-nearby');nearby.append(node('h2','附近知识'));for(const r of data.relations)nearby.append(button(r.other_star.name+' · '+r.label,()=>MindOSKnowledgeUniverse.selectStar(r.other_star.id)));root.append(nearby);
  if(!data.atom.unlocked){content.append(node('p','这是后续小节。请先主动进入相应小节，再学习或添加材料。','muted'));tools.hidden=toolbar.hidden=tabs.hidden=true;return;}
  tools.append(manualForm(),uploadForm(),generationForm(),searchForm());
  try{await load();}catch(e){report(e);}CourseAssistant.sync();
 }
 function report(e){if(!active())return;$('ks-error').hidden=false;$('ks-error').textContent=e.message;}
 function render(counts={}){if(!active())return;const tabs=$('ks-tabs');tabs.replaceChildren(button('总览',()=>{tab='overview';render(counts);}));for(const[k,n]of Object.entries(names))if(counts[k]||resources.some(r=>r.resource_type===k))tabs.append(button(n+(counts[k]?' · '+counts[k]:''),()=>{tab=k;render(counts);}));if(counts.examples||resources.some(r=>r.role==='example'))tabs.append(button('例子 · '+(counts.examples||''),()=>{tab='example';render(counts);}));for(const b of tabs.children){b.setAttribute('aria-pressed',String(b.textContent.startsWith(tab==='overview'?'总览':tab==='example'?'例子':names[tab])));}
  const content=$('ks-content');content.replaceChildren();
  if(tab==='overview'){const intro=node('section','','card ks-overview');intro.append(node('h2','理解这个知识点'),node('p',detail.atom.description),node('p','材料帮助理解。阅读、上传、生成和聊天都不会直接修改掌握记录。','muted'));intro.append(button('问导师这个知识点',()=>{focus=null;grounded=false;CourseAssistant.open();},true),button('开始本次学习计时',async()=>{await call('/api/study/sessions/start',{course_id:detail.atom.course_id,atom_id:detail.atom.atom_id,activity_type:'course_learning',source:'course',planned_minutes:25});await MindOSStudy.refresh();}));content.append(intro);}
  const visible=resources.filter(r=>tab==='overview'||(tab==='example'?r.role==='example':r.resource_type===tab));for(const r of visible){const card=MindOSResources.render(r);card.dataset.focused=String(r.id===focus);const actions=node('div','','action-row');if(r.file_url){const original=node('a','查看原文件','button secondary');original.href=r.file_url;original.target='_blank';original.rel='noopener noreferrer';actions.append(original);}actions.append(button('问导师这份材料',()=>ask(r,false)),button('只根据这份材料提问',()=>ask(r,true)));
   if(r.metadata.document){const label=node('label','选择页码（如 1-3,5）'),input=document.createElement('input');input.placeholder='1-3,5';input.setAttribute('aria-label','PDF 页码');label.append(input);card.append(label,button(r.status==='failed'?'重新处理选中页':'提取选中页面',async()=>{const target=path(),token=version,pages=parsePages(input.value);const v=await call('/api/resources/'+r.id+'/extract',{pages});await call(target+'/'+v.resource.id+'/link',{});if(token===version)await load();}));if(r.metadata.page_count)card.append(node('p',`原文共 ${r.metadata.page_count} 页；只提取你选择的页，不自动发送全文。`,'muted'));}
   if(r.resource_type==='reference'&&r.payload.url)actions.append(button('获取实际正文片段',async()=>{const target=path(),token=version;const v=await call('/api/resources/'+r.id+'/fetch',{});await call(target+'/'+v.resource.id+'/link',{});if(token===version)await load();}));
   if(r.resource_type==='practice')actions.append(button('进入独立实践',async()=>{const cid=detail.atom.course_id,aid=detail.atom.atom_id,typ=r.payload.linked_authentic_type;await openCourse(cid,detail.atom.section_ordinal,'feedback');await MindOSAuthentic.render($('course-feedback'),null,cid,{atom_id:aid,task_type:typ});},true));
   if(r.status==='ready'&&!r.metadata.document)actions.append(button('生成摘要',async()=>{const v=await call(path()+'/generate',{type:'summary',source_resource_id:r.id});if(!v.available)throw Error(v.note);await load();}));
   if(debug)actions.append(button('查看资料调试信息',async()=>{const info=await call('/api/resources/'+r.id+'/inspect');const box=node('details');box.open=true;box.append(node('summary','Resource Inspector'),node('pre',JSON.stringify(info,null,2),'ks-code'));card.append(box);}));
   actions.append(button('取消此知识点的关联',async()=>{if(!confirm('只取消当前知识点关联，资料与其他关联保留。'))return;await call(path()+'/'+r.id+'/link',{},'DELETE');if(focus===r.id)focus=null;await load();}),button('永久删除资料',async()=>{const info=await call('/api/resources/'+r.id);if(!confirm(`永久删除“${r.title}”？共有 ${info.mappings.length} 个知识点关联、${info.derivatives.length} 个派生材料。所有关联将移除；有派生材料时需先处理派生材料。`))return;await call('/api/resources/'+r.id,{confirm:true},'DELETE');if(focus===r.id)focus=null;await load();}));card.append(actions);content.append(card);}
  if(!visible.length&&tab!=='overview')content.append(node('p','当前筛选下没有材料。'));if(!resources.length&&tab==='overview')content.append(node('p','还没有学习材料。可以添加笔记、上传资料，或按需让模型生成图示与例子。','muted'));if(hasMore)content.append(button('加载更多材料',()=>load(true)));
 }
 function ask(r,only){focus=r.id;grounded=only;CourseAssistant.open();$('assistant-question').value=only?'只根据这份材料，解释我不理解的地方。':'请结合这份材料解释这个知识点。';$('assistant-question').focus();document.querySelectorAll('.ks-material').forEach(c=>c.dataset.focused=String(c.dataset.resourceId===focus));}
 function parsePages(value){const pages=[];for(const part of value.split(',')){const m=part.trim().match(/^(\d{1,5})(?:\s*-\s*(\d{1,5}))?$/);if(!m)throw Error('页码请写成 1-3,5');const a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<a||b-a>11)throw Error('每次最多选择 12 页');for(let p=a;p<=b;p++)pages.push(p);}if(pages.length>12||new Set(pages).size!==pages.length)throw Error('每次最多选择 12 个不同页码');return pages;}
 function form(title){const f=node('form','','ks-form');f.append(node('h3',title));return f;}
 function field(f,label,type='text',required=true){const l=node('label',label),i=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.required=required;l.append(i);f.append(l);return i;}
 function manualForm(){
  const f=form('添加自己的笔记或材料'),title=field(f,'材料名称'),kind=document.createElement('select');kind.setAttribute('aria-label','手动资料类型');for(const[k,n]of Object.entries(names).filter(([k])=>!['image','paper_excerpt'].includes(k))){const o=node('option',n);o.value=k;kind.append(o);}f.append(kind);const body=node('div');f.append(body);let fields={};
  function choose(label,values){const l=node('label',label),select=document.createElement('select');for(const[k,n]of values){const o=node('option',n);o.value=k;select.append(o);}l.append(select);body.append(l);return select;}
  function draw(){body.replaceChildren();fields={};const k=kind.value;
   if(k==='text')fields.text=field(body,'你的笔记','textarea');
   if(k==='formula'){fields.expression=field(body,'公式表达式');fields.format=choose('公式写法',[['latex','LaTeX 公式'],['plain','普通表达式']]);fields.explanation=field(body,'这条公式想说明什么','textarea',false);fields.variables=field(body,'符号含义（每行一个，如 x：未知数）','textarea',false);}
   if(k==='code'){fields.language=choose('代码语言',[['python','Python'],['javascript','JavaScript'],['sql','SQL'],['json','JSON'],['bash','Shell'],['cpp','C++'],['text','其他文字']]);fields.code=field(body,'代码（只阅读，不运行）','textarea');fields.description=field(body,'代码说明','textarea',false);}
   if(k==='reference'){fields.url=field(body,'公开资料地址','url');fields.description=field(body,'资料说明或已知摘要','textarea',false);body.append(node('p','只保存参考链接，获取正文前不会声称已读全文。','muted'));}
   if(k==='diagram'){fields.nodes=field(body,'图示节点（每行一个名称，最多 12 个）','textarea');fields.edges=field(body,'连线（每行写编号，如 1→2；可留空）','textarea',false);fields.explanation=field(body,'图示说明','textarea',false);}
   if(k==='practice'){fields.prompt=field(body,'实践任务说明','textarea');fields.task_type=choose('验证方式',[['explanation','用自己的话解释'],['analysis','辨析错误'],['design','应用设计'],['open_transfer','迁移应用']]);fields.expected_time=field(body,'预计分钟','number');fields.expected_time.value='10';fields.expected_time.min='1';fields.expected_time.max='120';body.append(node('p','保存任务只是准备材料。开始后进入原有独立实践流程，不新增评分。','muted'));}
  }
  kind.onchange=draw;draw();const submit=node('button','保存并关联','button secondary');submit.type='submit';f.append(submit);f.onsubmit=e=>{e.preventDefault();action(submit,'正在保存…',async()=>{const payload={};for(const[k,i]of Object.entries(fields))payload[k]=i.value;
   if(kind.value==='formula'){const variables={};for(const line of payload.variables.split('\n').filter(l=>l.trim())){const m=line.match(/^([^:：]+)[:：](.+)$/);if(!m)throw Error('符号含义请按 x：未知数 填写');variables[m[1].trim()]=m[2].trim();}payload.variables=variables;}
   if(kind.value==='code')payload.runnable=false;
   if(kind.value==='diagram'){payload.nodes=payload.nodes.split('\n').filter(l=>l.trim()).map((label,i)=>({id:'node'+(i+1),label:label.trim()}));payload.edges=payload.edges.split('\n').filter(l=>l.trim()).map(line=>{const m=line.match(/^(\d+)\s*(?:→|->)\s*(\d+)$/);if(!m)throw Error('连线请写成 1→2');return {from:'node'+m[1],to:'node'+m[2]};});}
   if(kind.value==='practice')payload.expected_time=Number(payload.expected_time);
   await call(path(),{type:kind.value,title:title.value,payload,...(kind.value==='text'?{role:'personal_note'}:{})});draw();await load();});};return f;
 }
 function uploadForm(){const f=form('上传图片、文字或 PDF'),file=field(f,'选择文件','file');file.accept='.png,.jpg,.jpeg,.pdf,.txt,.md';file.id='ks-upload-file';const caption=field(f,'图片说明或替代文字','textarea',false);caption.id='ks-upload-caption';f.append(node('p','图片最多 10 MB；PDF 30 MB；文字 5 MB。PDF 选页提取，不识别扫描图。图片问答目前只依据你写的说明。','muted'));const submit=node('button','上传并关联当前知识点','button secondary');submit.type='submit';f.append(submit);f.onsubmit=e=>{e.preventDefault();action(submit,'正在上传…',async()=>{const target=path(),token=version,selected=file.files[0];if(!selected)return;const max=selected.name.toLowerCase().endsWith('.pdf')?30*1024*1024:/\.(png|jpe?g)$/i.test(selected.name)?10*1024*1024:5*1024*1024;if(selected.size>max)throw Error('文件超过此类型大小限制');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(selected);});const v=await call('/api/resources/upload',{filename:selected.name,content_base64:encoded,alt:caption.value,caption:caption.value});await call(target+'/'+v.resource_id+'/link',{});if(token!==version)return;file.value='';tab='overview';await load();});};return f;}
 function generationForm(){const f=node('div','','ks-form');f.append(node('h3','按需生成辅助材料'),node('p','生成后仍需核对，不自动给整门课程生成。','muted'));for(const[k,n]of [['diagram','图示'],['example','例子'],['formula','公式解释'],['code','代码示例']])f.append(button('生成'+n,async()=>{const v=await call(path()+'/generate',{type:k});if(!v.available)throw Error(v.note);await load();}));return f;}
 function searchForm(){const f=form('寻找公开参考资料'),q=field(f,'资料检索词'),mode=document.createElement('select');mode.setAttribute('aria-label','资料检索入口');for(const[k,n]of [['public','免密钥 Wikipedia / GitHub（覆盖有限）'],['tavily','Tavily（需配置）'],['brave','Brave（需配置）']]){const o=node('option',n);o.value=k;mode.append(o);}f.append(mode,node('p','复用课程检索入口；结果只有标题和摘要，确认关联才保存，不冒充论文全文。','muted'));const result=node('div'),submit=node('button','检索标题与摘要','button secondary');submit.type='submit';f.append(submit,result);f.onsubmit=e=>{e.preventDefault();action(submit,'正在检索…',async()=>{const v=await call('/api/sources/search',{course_id:detail.atom.course_id,query:q.value,search_mode:mode.value});result.replaceChildren();for(const s of v.results){const row=node('article');row.append(node('strong',s.title),node('p',s.description||s.snippet||''),button('确认关联此参考链接',async()=>{await call(path(),{type:'reference',title:s.title,payload:{url:s.url,description:s.description||s.snippet||''}});await load();}));result.append(row);}if(!v.results.length)result.append(node('p','没有取得可用结果，未添加来源。'));});};return f;}
 function back(){version++;root.hidden=true;focus=null;grounded=false;$('knowledge-universe').hidden=false;CourseAssistant.sync();}
 function hide(){version++;root.hidden=true;focus=null;grounded=false;detail=null;}
 return {show,hide,back,active,selection,parsePages,enableDebug(value){debug=value===true;}};
})();
