/* Practice workspace. Uses the existing tutor, timing, resources and independent assessment. */
window.MindOSMission=(()=>{
 let selected=null,taskId=null,mission=null,focus=null,pages=[],grounded=false,serial=0;
 const labels={draft:'待确认计划',active:'进行中',paused:'暂停',completed:'已完成',abandoned:'已停止',planned:'待安排',ready:'可开始',blocked:'需要先处理',skipped:'已跳过'};
 const types={project:'项目',competition:'比赛',experiment:'实验',portfolio:'作品集',research:'研究',custom:'自定义'};
 const taskTypes={learn:'学习',implement:'实现',experiment:'实验',analyze:'分析',document:'文档',verify:'独立验证',reflect:'复盘',submit:'提交'};
 const artifactTypes={code:'代码',report:'报告',dataset:'数据集',benchmark:'性能记录',profile:'分析记录',image:'图片',log:'日志',model:'模型文件',document:'文档',submission:'提交材料',other:'其他'};
 const url=(mid,op='')=>'/api/missions/'+encodeURIComponent(mid)+(op?'/'+op:'');
 async function call(path,p,method){const r=await fetch(path,{method:method||(p===undefined?'GET':'POST'),headers:p===undefined?{}:{'Content-Type':'application/json'},body:p===undefined?undefined:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw Error(d.error||'实践操作暂未完成');return d;}
 function button(label,work,primary=false){const b=node('button',label,'button '+(primary?'primary':'secondary'));b.type='button';b.onclick=async()=>{b.disabled=true;const workspace=$('mission-workspace'),locked=workspace&&!workspace.hidden;if(locked){workspace.inert=true;workspace.setAttribute('aria-busy','true');}try{await work();}catch(e){showNotice(e.message);}finally{if(locked){workspace.inert=false;workspace.setAttribute('aria-busy','false');}if(b.isConnected)b.disabled=false;}};return b;}
 function input(parent,label,value='',type='text'){const l=node('label',label),i=node(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;else i.rows=3;i.setAttribute('aria-label',label);i.value=value??'';l.append(i);parent.append(l);return i;}
 function select(parent,label,value,options){const l=node('label',label),s=node('select');s.setAttribute('aria-label',label);for(const [id,name]of Object.entries(options)){const o=node('option',name);o.value=id;s.append(o);}s.value=value??'';l.append(s);parent.append(l);return s;}
 function check(parent,label,checked=false){const l=node('label','','mission-check'),i=node('input');i.type='checkbox';i.checked=checked;l.append(i,node('span',label));parent.append(l);return i;}
 function section(parent,title,cls=''){const s=node('section','','card mission-card '+cls);s.append(node('h2',title));parent.append(s);return s;}
 async function reload(){return show(selected,taskId);}
 function hide(){const r=$('mission-workspace');if(r)r.hidden=true;}
 async function show(mid=selected,tid=null){
  const version=++serial;invalidateNavigation();MindOSUniverse.hideStandalone();for(const id of ['welcome','review-view','course-view','course-management'])$(id).hidden=true;const root=$('mission-workspace');root.hidden=false;state.page='mission';state.data=null;state.courseId=null;state.missionSelection=null;$('breadcrumb').textContent='实践空间';root.replaceChildren(node('p','正在读取实践项目…','muted'));
  const list=await call('/api/missions');if(version!==serial||state.page!=='mission')return;
  selected=list.missions.some(m=>m.id===mid)?mid:list.missions[0]?.id||null;mission=null;focus=null;pages=[];grounded=false;
  root.replaceChildren(node('p','LEARNING BY DOING','eyebrow'),node('h1','把知识用起来'),node('p','记录你实际做的项目、实验和成果。项目完成不代表知识已经掌握，能力验证仍需要独立作答。','muted'));
  const toolbar=node('div','','action-row');toolbar.append(button('新建实践项目',()=>editor(root),true));for(const m of list.missions)toolbar.append(button(m.title+' · '+labels[m.status],()=>show(m.id)));root.append(toolbar);
  if(!selected){await recommendations(root);return;}
  const detail=await call(url(selected));if(version!==serial||state.page!=='mission')return;mission=detail.mission;
  taskId=mission.tasks.some(t=>t.id===tid)?tid:mission.tasks.find(t=>t.status==='active')?.id||mission.tasks.find(t=>t.status==='ready')?.id||mission.tasks[0]?.id||null;
  const t=mission.tasks.find(t=>t.id===taskId);if(t?.linked_course_id){try{const data=await call('/api/course?course_id='+encodeURIComponent(t.linked_course_id));if(version!==serial||state.page!=='mission')return;state.data=data;state.courseId=data.course.id;}catch(_){state.data=null;state.courseId=null;}}
  state.missionSelection={mission_id:selected,task_id:taskId};render(root);window.CourseAssistant?.sync?.();
 }
 async function editor(parent,m={}){
  const s=section(parent,m.id?'编辑实践项目':'创建实践项目','mission-editor');s.scrollIntoView({block:'start'});const title=input(s,'项目名称',m.title),description=input(s,'项目说明',m.description,'textarea'),outcome=input(s,'希望交付什么成果？',m.target_outcome,'textarea'),kind=select(s,'项目类型',m.mission_type||'project',types),due=input(s,'截止日期（可选）',m.deadline,'date'),priority=input(s,'优先级（1最高，5最低）',m.priority||2,'number');priority.min=1;priority.max=5;
  const goals=await call('/api/goals'),goal=select(s,'关联成长目标（可选）',m.goal_id||'',{'':'暂不关联',...Object.fromEntries(goals.goals.map(g=>[g.id,g.title]))});
  s.append(button(m.id?'保存修改':'确认创建',async()=>{const p={title:title.value,description:description.value,target_outcome:outcome.value,mission_type:kind.value,deadline:due.value||null,priority:Number(priority.value),goal_id:goal.value||null};const r=await call(m.id?url(m.id):'/api/missions',m.id?p:{...p,confirmed:true},m.id?'PATCH':'POST');await show(r.mission.id);},true),button('取消',()=>s.remove()));
 }
 function render(root){
  const header=section(root,mission.title,'mission-header');header.append(node('p',mission.description),node('p','预期交付：'+(mission.target_outcome||'请在编辑项目中明确成果')));if(mission.goal)header.append(button('关联目标：'+mission.goal.title,()=>MindOSGrowth.show(mission.goal_id)));header.append(node('p',`${labels[mission.status]} · 计划 v${mission.plan_version} · ${mission.deadline?'截止 '+mission.deadline:'未设置截止日期'}`,'muted'));
  const stats=node('div','','mission-stats');for(const [name,value]of [['任务',mission.progress.tasks_completed+'/'+mission.progress.tasks_total],['里程碑',mission.progress.milestones_completed+'/'+mission.progress.milestones_total],['实验记录',mission.progress.runs],['实际记录用时',mission.progress.actual_minutes+' 分钟']]){const cell=node('div');cell.append(node('strong',String(value)),node('small',name));stats.append(cell);}header.append(stats,node('small',mission.boundary,'muted'));
  const actions=node('div','','action-row');actions.append(button('编辑项目',()=>editor(root,mission)),button(mission.plan_version?'重新规划草稿':'生成计划草稿',async()=>{await call(url(selected,mission.plan_version?'replan':'plan/generate'),{reason:'USER_REQUESTED'});await reload();},true));
  for(const [status,label]of [['paused','暂停项目'],['active','恢复项目'],['completed','确认项目完成'],['abandoned','停止项目']])if(status!==mission.status)actions.append(button(label,async()=>{if(status==='completed'&&!confirm('仅确认交付完成，不标记知识掌握或成长目标达成。继续？'))return;await call(url(selected),{status},'PATCH');await reload();}));
  const outcome=select(actions,'实际项目结果',mission.outcome||'',{'':'尚未填写',success:'成果达到预期',partial:'部分达到预期',failed:'未达到预期',withdrawn:'主动撤回'});outcome.onchange=async()=>{if(outcome.value){try{await call(url(selected),{outcome:outcome.value},'PATCH');await reload();}catch(e){showNotice(e.message);}}};header.append(actions);
  if(mission.draft?.plan)reviewPlan(root);
  if(!mission.tasks.length){root.append(node('p','生成草稿后先审查与修改，再确认启用。模型建议不会自动开始任务。','muted'));return;}
  const layout=node('div','','mission-layout'),nav=node('aside','','mission-waypoints'),main=node('div','','mission-current');layout.append(nav,main);root.append(layout);
  for(const ms of mission.milestones){const box=node('article','','mission-waypoint');box.dataset.status=ms.status;box.append(node('h3',ms.ordinal+' · '+ms.title),node('p',ms.objective,'muted'),node('small',labels[ms.status]||ms.status));box.append(button(ms.metadata.locked?'取消固定里程碑':'固定里程碑',async()=>{await call(url(selected,`milestones/${ms.id}/lock`),{enabled:!ms.metadata.locked});await reload();}));for(const t of mission.tasks.filter(t=>t.milestone_id===ms.id)){const b=button(t.title+' · '+labels[t.status],()=>show(selected,t.id));b.classList.toggle('selected',t.id===taskId);b.dataset.taskId=t.id;box.append(b);}nav.append(box);}
  const task=mission.tasks.find(t=>t.id===taskId);if(task)renderTask(main,task);
  renderArtifacts(root,task);renderReflections(root,task);renderCandidates(root,task);
  if(mission.history.length>1){const history=node('details');history.append(node('summary','查看计划调整历史'));for(const h of mission.history)history.append(node('p',`v${h.version} · ${h.confirmed_at} · ${h.plan.milestones.map(s=>s.title).join(' → ')}`));root.append(history);}
 }
 function reviewPlan(root){
  const draft=structuredClone(mission.draft.plan),s=section(root,'审查实践计划');s.dataset.testid='mission-plan-review';s.append(node('p',mission.draft.source==='model'?'这是模型建议，确认前可以修改；不会写入能力状态。':'模型暂未提供有效计划，当前是可编辑的保守草稿，请结合项目要求修改。','muted'));
  const list=node('div');s.append(list);
  function draw(){list.replaceChildren();let preceding=[];
   for(const ms of draft.milestones){const d=node('details');d.open=true;d.append(node('summary',ms.title));const title=input(d,'里程碑名称',ms.title),objective=input(d,'这一阶段要完成什么？',ms.objective,'textarea'),due=input(d,'阶段截止日期（可选）',ms.due_date,'date'),required=check(d,'这是必需里程碑',ms.required),lock=check(d,'固定此里程碑',ms.locked);title.oninput=()=>ms.title=title.value;objective.oninput=()=>ms.objective=objective.value;due.oninput=()=>ms.due_date=due.value||null;required.onchange=()=>ms.required=required.checked;lock.onchange=()=>ms.locked=lock.checked;
    const tasks=node('div');d.append(tasks);
    for(const t of ms.tasks){const box=node('div','','mission-draft-task');box.append(node('h4',taskTypes[t.task_type]));const name=input(box,'任务名称',t.title),desc=input(box,'任务说明',t.description,'textarea'),kind=select(box,'任务类型',t.task_type,taskTypes),minutes=input(box,'原始预计分钟',t.estimated_minutes,'number'),req=check(box,'这是必需任务',t.required),locked=check(box,'固定此任务',t.locked);name.oninput=()=>t.title=name.value;desc.oninput=()=>t.description=desc.value;kind.onchange=()=>{t.task_type=kind.value;if(kind.value!=='experiment')t.experiment={};};minutes.oninput=()=>t.estimated_minutes=Number(minutes.value);req.onchange=()=>t.required=req.checked;locked.onchange=()=>t.locked=locked.checked;
     const deps=node('details');deps.append(node('summary','前置任务'));for(const prior of preceding){const c=check(deps,prior.title,t.dependencies.includes(prior.key));c.onchange=()=>t.dependencies=c.checked?[...t.dependencies,prior.key]:t.dependencies.filter(k=>k!==prior.key);}box.append(deps);
     const deliverables=node('details');deliverables.append(node('summary','完成前必须交付的产出'));for(const [kind,label]of Object.entries(artifactTypes)){const c=check(deliverables,label,t.artifact_types.includes(kind));c.onchange=()=>t.artifact_types=c.checked?[...t.artifact_types,kind]:t.artifact_types.filter(k=>k!==kind);}box.append(deliverables,button('移除此任务',()=>{ms.tasks=ms.tasks.filter(x=>x!==t);for(const m of draft.milestones)for(const x of m.tasks)x.dependencies=x.dependencies.filter(k=>k!==t.key);draw();}));tasks.append(box);preceding.push(t);
    }
    d.append(button('增加任务',()=>{ms.tasks.push({key:'task_'+crypto.randomUUID().replaceAll('-',''),title:'新的执行任务',task_type:'implement',description:'请描述要实际完成的操作。',required:true,locked:false,priority:2,estimated_minutes:25,dependencies:[],artifact_types:[],resource_ids:[],experiment:{},linked_course_id:null,linked_atom_id:null,linked_growth_task_id:null});draw();}),button('移除此里程碑',()=>{const removed=new Set(ms.tasks.map(t=>t.key));draft.milestones=draft.milestones.filter(x=>x!==ms);for(const m of draft.milestones)for(const x of m.tasks)x.dependencies=x.dependencies.filter(k=>!removed.has(k));draw();}));list.append(d);
   }
  }
  draw();s.append(button('增加里程碑',()=>{draft.milestones.push({key:'milestone_'+crypto.randomUUID().replaceAll('-',''),title:'新的里程碑',objective:'请描述这一阶段的实际成果。',required:true,locked:false,planned_minutes:null,due_date:null,gate:{artifact_types:[],require_run:false},tasks:[{key:'task_'+crypto.randomUUID().replaceAll('-',''),title:'新的执行任务',task_type:'implement',description:'请描述要实际完成的操作。',required:true,locked:false,priority:2,estimated_minutes:25,dependencies:[],artifact_types:[],resource_ids:[],experiment:{},linked_course_id:null,linked_atom_id:null,linked_growth_task_id:null}]});draw();}),button('确认计划并启用项目',async()=>{await call(url(selected,'plan/confirm'),{confirm:true,draft_version:mission.draft_version,plan:draft});await reload();},true));
 }
 function renderTask(root,t){
  const s=section(root,t.title);s.dataset.testid='mission-current-task';s.append(node('p',`${taskTypes[t.task_type]} · ${labels[t.status]} · 预计 ${t.duration.personalized_minutes} 分钟`),node('small',`原始估时 ${t.estimated_minutes} 分钟；${t.duration.estimate_source}`,'muted'),node('p',t.description));if(t.blocked_reasons.length)s.append(node('p','先处理：'+t.blocked_reasons.join('；'),'notice'));
  const actions=node('div','','action-row');if(!['active','completed','skipped'].includes(t.status))actions.append(button('开始任务',async()=>{await call(url(selected,`tasks/${t.id}/start`),{});await reload();},true));if(t.status==='active'){actions.append(button('开始记录本次用时',async()=>{await call(url(selected,`tasks/${t.id}/study/start`),{planned_minutes:t.duration.personalized_minutes});await MindOSStudy.refresh();},true),button('确认任务完成',async()=>{await call(url(selected,`tasks/${t.id}/complete`),{});await reload();showNotice('任务交付已记录。可以花 1 分钟写下发现、偏差与下一步。');}));}
  if(t.status!=='completed')actions.append(button(t.status==='skipped'?'恢复任务':'跳过任务',async()=>{await call(url(selected,`tasks/${t.id}/${t.status==='skipped'?'resume':'skip'}`),{});await reload();}));actions.append(button(t.metadata.locked?'取消固定任务':'固定任务',async()=>{await call(url(selected,`tasks/${t.id}/lock`),{enabled:!t.metadata.locked});await reload();}),button('任务设置与关联课程',()=>taskEditor(s,t)));if(t.linked_course_id)actions.append(button('打开关联课程',()=>openCourse(t.linked_course_id)));s.append(actions,node('p','结束计时不会自动完成任务；产出上传和任务完成也不改变掌握记录。','muted'));
  if(t.metadata.resource_ids.length){s.append(node('h3','参考学习资料'));for(const rid of t.metadata.resource_ids){const row=node('p','正在读取资料…');s.append(row);call('/api/resources/'+rid).then(r=>{if(row.isConnected)row.replaceChildren(MindOSResourceRenderer.render(r.resource));}).catch(()=>row.textContent='这份参考资料已不可用。');}}
  if(t.task_type==='experiment')renderExperiment(root,t);
 }
 async function taskEditor(parent,t){
  const s=section(parent,'任务设置'),title=input(s,'任务名称',t.title),desc=input(s,'任务说明',t.description,'textarea'),req=check(s,'这是必需任务',t.metadata.required),minutes=input(s,'原始预计分钟',t.estimated_minutes,'number'),course=select(s,'关联课程',t.linked_course_id||'',{'':'暂不关联',...Object.fromEntries(state.courses.filter(c=>!c.deleted_at).map(c=>[c.id,c.title||c.name]))}),atom=select(s,'关联知识点','',{'':'使用当前小节'});const materials=node('div'),materialChecks=[],requiredArtifacts=node('details');requiredArtifacts.append(node('summary','任务必须交付的产出'));const requiredKinds=[];for(const [kind,label]of Object.entries(artifactTypes))requiredKinds.push({kind,c:check(requiredArtifacts,label,t.metadata.artifact_types.includes(kind))});s.append(materials,requiredArtifacts);const growthTasks=mission.goal?await call('/api/goals/'+mission.goal_id+'/roadmap'):{roadmap:null},growthLink=select(s,'关联成长路线任务（可选）',t.linked_growth_task_id||'',{'':'暂不关联',...Object.fromEntries((growthTasks.roadmap?.tasks||[]).map(x=>[x.id,x.title]))});
  async function loadMaterials(){materials.replaceChildren(node('h3','参考学习资料'));materialChecks.length=0;if(!course.value||!atom.value){materials.append(node('p','选择课程与知识点后可添加已有学习资料。','muted'));return;}const r=await call('/api/courses/'+course.value+'/atoms/'+atom.value+'/resources');for(const item of r.resources){materialChecks.push({id:item.id,c:check(materials,item.title,t.metadata.resource_ids.includes(item.id))});}if(!r.resources.length)materials.append(node('p','当前知识点暂未关联材料，可先在知识空间添加。','muted'));}
  async function atoms(){atom.replaceChildren(new Option('使用当前小节','')); if(course.value){const r=await call('/api/course?course_id='+encodeURIComponent(course.value));for(const a of r.knowledge?.atoms||[])if(a.unlocked)atom.add(new Option(a.title,a.id));atom.value=t.linked_course_id===course.value?t.linked_atom_id||'':'';}await loadMaterials();}atom.onchange=()=>loadMaterials().catch(e=>showNotice(e.message));course.onchange=()=>atoms().catch(e=>showNotice(e.message));await atoms();
  s.append(button('保存任务设置',async()=>{await call(url(selected,`tasks/${t.id}`),{title:title.value,description:desc.value,required:req.checked,estimated_minutes:Number(minutes.value),linked_course_id:course.value||null,linked_atom_id:atom.value||null,resource_ids:materialChecks.filter(x=>x.c.checked).map(x=>x.id),artifact_types:requiredKinds.filter(x=>x.c.checked).map(x=>x.kind),linked_growth_task_id:growthLink.value||null},'PATCH');await reload();},true),button('取消',()=>s.remove()));
 }
 function pairs(value,numeric=false){const out={};for(const line of value.split('\n').filter(l=>l.trim())){const i=line.indexOf('=');if(i<1)throw Error('每行请填写 名称=值');const k=line.slice(0,i).trim(),v=line.slice(i+1).trim();if(k in out)throw Error('名称不能重复');if(numeric&&!Number.isFinite(Number(v)))throw Error('实验指标请填写有限数值');out[k]=numeric?Number(v):v!==''&&Number.isFinite(Number(v))?Number(v):v;}return out;}
 function renderExperiment(root,t){
  const s=section(root,'实验记录'),exp=t.metadata.experiment;s.append(node('p','只记录你实际运行的实验，MindOS 不执行代码。','muted'));const hypothesis=input(s,'待验证假设',exp.hypothesis,'textarea'),setup=input(s,'实验环境与步骤',exp.setup,'textarea'),vars=input(s,'预期变量（每行 名称=值）',Object.entries(exp.variables||{}).map(([k,v])=>k+'='+v).join('\n'),'textarea'),expected=input(s,'预期结果',exp.expected_result,'textarea');s.append(button('保存实验说明',async()=>{await call(url(selected,`tasks/${t.id}`),{experiment:{hypothesis:hypothesis.value,setup:setup.value,variables:pairs(vars.value),expected_result:expected.value}},'PATCH');await reload();}));
  const records=mission.runs.filter(r=>r.task_id===t.id),choices=[];for(const r of records){const box=node('article','','mission-run'),cb=check(box,'实验 '+r.run_index+' · '+r.created_at);choices.push({cb,id:r.id});box.append(node('p','参数：'+Object.entries(r.parameters).map(([k,v])=>k+'='+v).join('，')),node('p','指标：'+Object.entries(r.metrics).map(([k,v])=>k+'='+v).join('，')),node('p',r.notes));s.append(box);}
  if(records.length>=2)s.append(button('比较选中实验（2–5条）',async()=>{const r=await call(url(selected,`tasks/${t.id}/compare`),{run_ids:choices.filter(x=>x.cb.checked).map(x=>x.id)});const box=section(s,'同名指标比较');for(const metric of r.comparison){const table=node('table');table.append(node('caption',metric.metric));for(const v of metric.values){const row=node('tr');row.append(node('th','实验 '+v.run_index),node('td',String(v.value)));table.append(row);}box.append(table,node('p',`最小值 ${metric.minimum} · 最大值 ${metric.maximum}`));}box.append(node('p',r.boundary,'muted'));}));
  if(t.status==='active')s.append(button('记录一次实验',()=>{const form=section(s,'本次实际实验'),params=input(form,'参数（每行 名称=值）','','textarea'),metrics=input(form,'结果指标（每行 名称=数值；单位写在名称中）','','textarea'),notes=input(form,'观察、结论与限制','','textarea'),attachments=artifactChecks(form,t);form.append(button('保存实际记录',async()=>{await call(url(selected,`tasks/${t.id}/runs`),{parameters:pairs(params.value),metrics:pairs(metrics.value,true),notes:notes.value,artifact_ids:attachments()});await reload();},true));}));
 }
 function artifactChecks(parent,t){const values=[];for(const a of mission.artifacts.filter(a=>!t||a.task_id===t.id)){const c=check(parent,a.title+' · v'+a.version);values.push({id:a.id,c});}return ()=>values.filter(x=>x.c.checked).map(x=>x.id);}
 function renderArtifacts(root,t){
  const s=section(root,'实践产出');s.append(node('p','代码、日志和配置文件请先去掉密钥。文字最多 5 MB、图片 10 MB、PDF与模型 30 MB；大日志只上传相关片段。文件不会被运行。','muted'));
  s.append(button('上传产出',()=>{const form=section(s,'上传实践产出'),type=select(form,'产出类型','report',artifactTypes),file=input(form,'选择文件','','file'),caption=input(form,'说明（图片导师只读取这段文字）','','textarea'),parent=select(form,'作为已有产出的新版本（可选）','',{'':'这是新产出',...Object.fromEntries(mission.artifacts.filter(a=>a.task_id===t?.id).map(a=>[a.id,a.title+' · v'+a.version]))});file.accept='.txt,.md,.pdf,.png,.jpg,.jpeg,.py,.cu,.c,.cpp,.h,.json,.csv,.log,.yaml,.yml,.toml,.ini,.cfg,.bin,.pt,.pth,.onnx,.safetensors,.gguf';form.append(button('保存产出',async()=>{const targetMission=selected,targetTask=t?.id||null;const f=file.files[0];if(!f)throw Error('请选择文件');if(f.size>31457280)throw Error('文件超过 30 MB，请先截取片段');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});await call(url(targetMission,'artifacts/upload'),{filename:f.name,artifact_type:type.value,task_id:targetTask,caption:caption.value,parent_artifact_id:parent.value||null,content_base64:data});await reload();},true));},true));
  for(const a of mission.artifacts.filter(a=>!t||a.task_id===t.id)){const box=node('article','','mission-artifact');box.append(node('h3',a.title),node('p',`${artifactTypes[a.artifact_type]} · v${a.version}${a.parent_artifact_id?' · 有上一版本':''} · ${a.created_at}`,'muted'));box.append(button('预览与询问导师',()=>preview(box,a)),button('保存为学习资料',async()=>{if(!t?.linked_course_id||!t.linked_atom_id)throw Error('请先关联课程与知识点');if(!confirm('创建一份独立的学习资料，不改变掌握记录。继续？'))return;await call(url(selected,`artifacts/${a.id}/promote`),{confirm:true,course_id:t.linked_course_id,atom_id:t.linked_atom_id,pages:a.id===focus?pages:[]});showNotice('已创建派生学习资料，可在关联知识点查看。');}),button('删除产出',async()=>{if(!confirm('永久删除这份产出？有版本、复盘或评估引用时会保留。'))return;await call(url(selected,`artifacts/${a.id}`),{confirm:true},'DELETE');await reload();}));s.append(box);}
 }
 function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length&&rows.length<40;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&[',','\n'].includes(c)){row.push(cell);cell='';if(c==='\n'){rows.push(row);row=[];}}else if(c!=='\r')cell+=c;}if(row.length||cell){row.push(cell);rows.push(row);}const table=node('table');for(const [i,values]of rows.entries()){const tr=node('tr');for(const v of values.slice(0,12))tr.append(node(i?'td':'th',v));table.append(tr);}return table;}
 function jsonTree(value,depth=0){if(depth>5||value===null||typeof value!=='object')return node('pre',JSON.stringify(value));const d=node('details');d.open=depth<2;d.append(node('summary',Array.isArray(value)?'列表 · '+value.length:'对象 · '+Object.keys(value).length));for(const [k,v]of Object.entries(value).slice(0,40)){const row=node('div');row.append(node('strong',k),jsonTree(v,depth+1));d.append(row);}return d;}
 async function preview(parent,a,chosenPages=[]){
  parent.querySelector('.mission-preview')?.remove();const box=node('div','','mission-preview');parent.append(box);const r=await call(url(selected,`artifacts/${a.id}/preview`),{pages:chosenPages});if(!box.isConnected)return;focus=a.id;pages=chosenPages;grounded=true;box.append(node('p',r.note,'muted'));
  if(a.mime_type==='application/pdf'){const p=input(box,'选择 PDF 页码（例如 1,2）',chosenPages.join(','));box.append(button('读取所选页码',()=>preview(parent,a,p.value.split(/[,，]/).filter(Boolean).map(Number))));}
  if(a.metadata.format==='image'){const image=node('img');image.src=a.file_url;image.alt=a.metadata.caption||'实践图片';box.append(image);}
  else if(a.artifact_type==='code')box.append(MindOSResourceRenderer.code({language:a.metadata.filename.split('.').pop(),code:r.text,description:'仅预览，不运行'}));
  else if(a.metadata.filename.toLowerCase().endsWith('.csv'))box.append(csv(r.text));
  else if(a.metadata.filename.toLowerCase().endsWith('.json')){try{box.append(jsonTree(JSON.parse(r.text)));}catch(_){box.append(node('pre',r.text));}}
  else if(r.text)box.append(node('pre',r.text));
  const only=check(box,'导师只根据此产出回答',true);only.onchange=()=>grounded=only.checked;box.append(node('p','已选为导师上下文，使用右下角悬浮导师提问。仅传入有限片段；不据此判断能力。','muted'));
 }
 function renderReflections(root,t){
  const s=section(root,'一分钟复盘');s.append(node('p','最关键的发现是什么？哪里与预期不同？下一步需要避免什么？','muted'));const kind=select(s,'复盘方向','retrospective',{what_worked:'有效做法',what_failed:'遇到的问题',lesson_learned:'学到的经验',next_step:'下一步',retrospective:'阶段回顾'}),body=input(s,'写下你自己的复盘','','textarea'),confirmed=check(s,'我确认这是自己的复盘内容');s.append(button('确认保存复盘',async()=>{await call(url(selected,'reflections'),{task_id:t?.id||null,milestone_id:t?.milestone_id||null,reflection_type:kind.value,content:body.value,confirmed:confirmed.checked,artifact_ids:focus?[focus]:[]});await reload();},true));for(const r of mission.reflections)s.append(node('p',r.content),node('small',r.created_at,'muted'));
 }
 function renderCandidates(root,t){
  const s=section(root,'独立能力验证');s.append(node('p','产出可以提出“我能做什么”的待验证声明。模型点评只指出可能的问题；随后生成新的陌生任务，仍由你独立作答。','muted'));const capability=select(s,'关联目标能力（可选）','',{'':'暂不关联',...Object.fromEntries((mission.goal?.graph?.capabilities||[]).map(c=>[c.id,c.name]))});const ids=artifactChecks(s,t),claim=input(s,'这份产出支持哪项能力声明？','','textarea'),type=select(s,'声明方向','implementation',{application:'应用',transfer:'迁移',tool_use:'工具使用',problem_solving:'问题解决',implementation:'实现',analysis:'分析'});s.append(button('确认保存待验证候选',async()=>{await call(url(selected,'evidence/analyze'),{artifact_ids:ids(),claim:claim.value,claim_type:type.value,capability_id:capability.value||null,confirmed:true});await reload();},true));
  for(const c of mission.evidence_candidates){const box=node('article','','mission-candidate');box.append(node('h3',c.claim),node('p','待验证候选 · 不代表已掌握','muted'));for(const obs of c.review.observations||[])box.append(node('p','模型辅助观察：'+obs));if(c.review.note)box.append(node('p',c.review.note,'muted'));const verificationType=select(box,'独立任务形式','design',{design:'应用设计',open_transfer:'开放迁移'});box.append(button(c.verification.authentic_task_id?'打开原独立验证':'生成独立陌生任务',async()=>{if(!t?.linked_course_id||!t.linked_atom_id)throw Error('请先关联已有课程和知识点');const r=c.verification.authentic_task_id?await call(url(selected,`evidence/${c.id}`)):await call(url(selected,`evidence/${c.id}/verify`),{course_id:t.linked_course_id,atom_id:t.linked_atom_id,task_type:verificationType.value,confirm:true,...(t.linked_growth_task_id&&c.capability_id?{linked_growth_task_id:t.linked_growth_task_id}:{})});const v=r.verification||r.candidate.verification;await openCourse(v.course_id,undefined,'feedback');await MindOSAuthentic.render($('course-feedback'),null,v.course_id,null,v.authentic_task_id);},true));if(mission.goal)box.append(button('按原规则检查成长目标',()=>MindOSGrowth.show(mission.goal_id,null,true)));if(c.verification.authentic_task_id)box.append(button('读取验证结果',async()=>{const r=await call(url(selected,`evidence/${c.id}`));box.append(node('p',r.task?.result?`独立模型辅助评分：${r.task.result.score??'不可用'}；${r.independent_observation_available?'符合原校准规则':'尚不满足独立校准条件'}`:'尚未独立提交答案'),node('small',r.boundary,'muted'));}));s.append(box);}
 }
 async function recommendations(root,gid=null){
  const r=await call('/api/missions/recommendations'+(gid?'?goal_id='+encodeURIComponent(gid):''));if(!root.isConnected)return;const s=section(root,'把成长目标带进实践');for(const item of r.recommendations){s.append(node('h3',item.title),node('p',item.reason));s.append(button(item.mission_id?'继续已有实践':'审查并创建实践项目',()=>item.mission_id?show(item.mission_id):editor(s,{goal_id:item.goal_id,title:item.title,description:item.gaps?.join('、')||''})));}s.append(button('查看全部实践项目',()=>show()));
 }
 async function dashboard(root){const r=await call('/api/missions');if(!root.isConnected)return;const active=r.missions.filter(m=>m.status==='active').slice(0,3);if(!active.length)return;const s=section(root,'当前实践项目');for(const m of active)s.append(button(m.title+' · '+m.progress.tasks_completed+'/'+m.progress.tasks_total+' 个任务',()=>show(m.id)));s.append(node('small','实践建议最多三项；用时和完成情况不代表能力。','muted'));}
 function selection(){if(state.page!=='mission'||!mission)return null;const t=mission.tasks.find(t=>t.id===taskId);if(!t?.linked_course_id||!state.data)return null;const atom=state.data.knowledge?.atoms.find(a=>a.id===t.linked_atom_id);return {mission_id:selected,task_id:taskId,focused_artifact_id:focus,artifact_grounded:grounded,pages,current_context:{section_ordinal:atom?.section||state.data.section.ordinal,knowledge_atom_id:t.linked_atom_id},label:mission.title+' · '+t.title};}
 document.addEventListener('DOMContentLoaded',()=>{$('mission-open').onclick=()=>show().catch(e=>showNotice(e.message));});
 return {show,hide,recommendations,dashboard,selection};
})();
